// 本文件由你上传的“绳结.mmap”自动整理生成。
export const CATEGORIES = [
  {
    "id": "cat_01",
    "name": "圈结/套结",
    "color": "#47C6FF",
    "count": 29
  },
  {
    "id": "cat_02",
    "name": "编结",
    "color": "#B56DFF",
    "count": 9
  },
  {
    "id": "cat_03",
    "name": "多圈结",
    "color": "#48E6A0",
    "count": 11
  },
  {
    "id": "cat_04",
    "name": "套结",
    "color": "#FFB84D",
    "count": 72
  },
  {
    "id": "cat_05",
    "name": "摩擦结",
    "color": "#FF6B6B",
    "count": 16
  },
  {
    "id": "cat_06",
    "name": "八字结系列",
    "color": "#67E8F9",
    "count": 8
  },
  {
    "id": "cat_07",
    "name": "特殊绳结",
    "color": "#F472B6",
    "count": 18
  },
  {
    "id": "cat_08",
    "name": "反手结系列",
    "color": "#A3E635",
    "count": 20
  },
  {
    "id": "cat_09",
    "name": "绑扎类",
    "color": "#FACC15",
    "count": 16
  },
  {
    "id": "cat_10",
    "name": "连接结",
    "color": "#60A5FA",
    "count": 29
  },
  {
    "id": "cat_11",
    "name": "快松结",
    "color": "#FB7185",
    "count": 14
  },
  {
    "id": "cat_12",
    "name": "称人结系列",
    "color": "#C084FC",
    "count": 16
  },
  {
    "id": "cat_13",
    "name": "绳尾结",
    "color": "#34D399",
    "count": 12
  }
]

export const KNOTS = [
  {
    "id": "k001",
    "name": "优胜美地称人结",
    "english": "Yosemite Bowline；Bowline with Yosemite Finish；Retraced Bowline；Tucked Bowline",
    "alias": "優勝美地布林結",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "优胜美地称人结比一般的称人结更加牢固。人们把称人结的自由端绕在绳圈的一端，然后将自由端从绳结处拉回来---通常被称作“优胜美地终端”。这类绳结用途广泛，登山者可以很轻松地用它把攀登绳索套在自己的背带上。八字环结是最常见的选择，因为人们对它更熟悉。优胜美地称人结的优点有，当潮湿、结冰的时候容易解开，一只手就有可能绑好，绳结更简单，便于人们检查。建议把优胜美地称人结加个绳尾结比如双重反手结，这样就会更加牢固和安全。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k001.jpg"
  },
  {
    "id": "k002",
    "name": "中间八字结",
    "english": "In-Line Figure 8 Loop；Directional Figure 8 Loop；Single Figure Eight on the Bight",
    "alias": "",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "中间八字结是一种套结。可以在绳子中间打结，无需使用绳子端部。该套结仅可在一个方向受载，否则绳结会被破坏。它可以用在吊拉绳中，形成可用作手环的套结。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k002.jpg"
  },
  {
    "id": "k003",
    "name": "爱德华兹称人结",
    "english": "Edwards Bowline；Butler's Bowline；Harry Butler's Yosemite Bowline",
    "alias": "",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "爱德华兹称人结是一种用于攀爬的环形结。它比常见的称人结更安全。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k003.jpg"
  },
  {
    "id": "k004",
    "name": "水中称人结",
    "english": "Water Bowline；Clove Hitch Bowline",
    "alias": "水上称人结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "水中称人结是专为潮湿环境中使用的一种绳结，例如在拖动一条船时，而其他绳结会打滑或死结。虽然结成后的外观与双称人结类似,但水中称人结在绳尾部分用双套结形成一个绳环。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k004.jpg"
  },
  {
    "id": "k005",
    "name": "活称人结",
    "english": "Running Bowline；Running Bowline Knot",
    "alias": "",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "活称人结是一种套索，结构上与标准称人结有关。像大多数活结，活称人结在受拉时会自动张紧，但当拉力消除时会解开。与标准称人结一样，它容易滑动，甚至在长期使用也容易解开。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k005.jpg"
  },
  {
    "id": "k006",
    "name": "RAPALA结",
    "english": "Rapala Knot",
    "alias": "",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "RAPALA结常用于钓鱼，是一个绳端环结，用于固定诱饵或者需要自由、自然运动的苍蝇。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k006.jpg"
  },
  {
    "id": "k007",
    "name": "SCAFFOLD结",
    "english": "Scaffold Knot；Triple Overhand Noose",
    "alias": "三重反手套索结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "SCAFFOLD结用于将绳索连接到登山扣、卸扣或导轨上。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k007.jpg"
  },
  {
    "id": "k008",
    "name": "捕兽结",
    "english": "Fisherman's Eye；Middleman's Knot；Fisherman's Loop；Englishman's Loop；True Lover's Knot",
    "alias": "络头结；中间人结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "补兽结是一种由至少四种不同方法其一结在绳圈上的有用绳结，其中一种绳结被称作同心结。该绳结曾经常被攀岩绳上的中间人使用，但如今已被更好的绳结（如蝴蝶结）替代。钓鱼者也使用它结成一个主环，但是也有更适用于此的绳结，如络头结。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k008.jpg"
  },
  {
    "id": "k009",
    "name": "九字结",
    "english": "Figure Nine Loop；Figure-of-Nine Loop；Figure 9",
    "alias": "",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "攀岩者使用，九字结在绳子上形成一个固定的环。它有时被用来代替八字结把绳子固定在一个锚点上。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k009.jpg"
  },
  {
    "id": "k010",
    "name": "卡尔梅克结",
    "english": "Kalmyk Loop；Slipped Inuit Bowline",
    "alias": "卡尔梅克环",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "西方人大多数不认识卡尔梅克结，但在俄罗斯则很普遍，并且在需要固定线环时经常用来代替常见的称人结。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k010.jpg"
  },
  {
    "id": "k011",
    "name": "牧童结",
    "english": "Lariat Loop；Honda Knot；Bowstring Knot",
    "alias": "本田结；套索结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "牧童结往往被牛仔们用做套牛和马的套索。特别是当其捆绑在硬绳上时，圆形的形状有助于它沿着环绕的绳子自由滑动。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k011.jpg"
  },
  {
    "id": "k012",
    "name": "八字套结",
    "english": "Figure Eight Loop；Flemish Loop；Figure Eight on the Bight",
    "alias": "八字结绳耳；双八字结；八字结绳圈",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "八字套结用于在绳子端部形成一个固定的绳环。它打结相对容易，并且牢固，但是重载后会非常难以解开。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k012.jpg"
  },
  {
    "id": "k013",
    "name": "八字返穿结",
    "english": "Figure Eight Follow Through；Figure Eight Retrace；Rerouted Figure Eight Loop；Threaded Figure Eight Loop",
    "alias": "穿式八字结；翻穿双八字结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "八字返穿结常用于攀岩和洞穴探险（绳子张力中等），用于在绳子端部或环绕物体形成一个固定的绳环。它解开相对容易并且牢固，但是重载后会变得难以解开。当绳结必须系在无法轻易套上绳环的物体时，可使用“重新编结”的方法。特别的，它可用于将绳子系在攀岩安全带上。双环称人结可以完成同样的任务，打结更快并且不会死结，但是对于初学者来说，八字返穿结更容易上手，可快速检查打结是否正确。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k013.jpg"
  },
  {
    "id": "k014",
    "name": "蝴蝶结",
    "english": "Alpine Butterfly；Lineman's Loop；Butterfly Loop；Lineman's Rider",
    "alias": "阿尔卑斯蝴蝶结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "蝴蝶结用于在绳子中央形成一个固定的绳环。它可以系在绳索上，而无需使用绳子端部；当系绑很长的登山绳时，它很有用。蝴蝶结的打法非常容易检查，可以在任何方向受拉，带手套也可以打结。当需要固定的绳环时，通常会使用该结。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k014.jpg"
  },
  {
    "id": "k015",
    "name": "蝴蝶结（2）",
    "english": "Alpine Butterfly（Hand Method）；Lineman's Loop；Butterfly Loop；Lineman's Rider",
    "alias": "阿尔卑斯蝴蝶结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "蝴蝶结用于在绳子中央形成一个固定的绳环。它可以系在绳索上，而无需使用绳子端部；当系绑很长的登山绳时，它很有用。蝴蝶结的打法非常容易检查，可以在任何方向受拉，带手套也可以打结。当需要固定的绳环时，通常会使用该结。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k015.jpg"
  },
  {
    "id": "k016",
    "name": "斯科特锁定称人结",
    "english": "Scott's Locker Bwoline；Secured Bowline",
    "alias": "安全称人结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "斯科特锁定称人结是一种用于攀爬的环形结。它比常见的称人结更安全。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k016.jpg"
  },
  {
    "id": "k017",
    "name": "点滴环结",
    "english": "Dropper Loop",
    "alias": "血亲丁字结；滴管环结；点滴瓶结；血液循环滴管结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "点滴环结通常用于多钩鱼线。它位于长线的中间并形成一个垂直于该线的环。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k017.jpg"
  },
  {
    "id": "k018",
    "name": "双圈索结",
    "english": "Poacher's Knot；Tenkara One Knot；Double Overhand Sliding Loop；Double Overhand Noose；Stangle Snare；Two-Turn Scaffold Knot；Surveyor's Knot；Barrel Knot；DOND（Double Overhand Noose Knot）；Evans Knot...",
    "alias": "主线双联结；偷猎者结；双反手滑套结；DON结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "双圈套结是一种非常牢固的绳结，被登山者用于捆绑绳索和登山用铁索。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k018.jpg"
  },
  {
    "id": "k019",
    "name": "双龙结",
    "english": "Double Dragon；Double Dragon Loop",
    "alias": "",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "虽然不为人知，但是双龙结是一个极好的绳尾结，结绳快速而且容易。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k019.jpg"
  },
  {
    "id": "k020",
    "name": "双环称人结",
    "english": "Double Bowline；Round Turn Bowline；Double-Knotted Bowline",
    "alias": "双布林结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "双环称人结是用于攀岩的两种常用绳结之一，另一个是八字套结。与八字套结相比，双称人结的一个优点是系重后更容易解开。虽然它比标准的称人结牢固，但是双环称人结没有八字套结牢固。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k020.jpg"
  },
  {
    "id": "k021",
    "name": "双反手环",
    "english": "Surgeon's Loop；Double Loop；Double Overhand Loop",
    "alias": "外科环",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "双反手环是一种结实、容易打结的固定绳环，通常与鱼线一起使用。此绳结有点笨重，但在绳线和引导绳端部快速结成牢固的绳环并连接绳环时非常棒。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k021.jpg"
  },
  {
    "id": "k022",
    "name": "双重单结",
    "english": "Loop Knot；Overhand Loop",
    "alias": "反手结绳耳",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "双重单结是一个简单的绳结，它在一条绳子上形成一个固定的绳环。在绳圈上绑一个反手结，它可以沿绳索绑在绳子的任何地方。该结可用于连接夹子，钩子和其他绳索等，但是它的缺点是，当绳索承受负荷时它可能会变成死结，可能需要剪断绳结。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k022.jpg"
  },
  {
    "id": "k023",
    "name": "滑八字结",
    "english": "Slip Figure Eight；Slipped Figure Eight Knot",
    "alias": "活八字结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "这种绳结用来在绳索中间形成一个可调节的套索。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k023.jpg"
  },
  {
    "id": "k024",
    "name": "滑结",
    "english": "Slipped Overhand Knot；Slip Knot；Running Knot；Noose",
    "alias": "活结；简单的活索",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "活结和滑结是大多数绳结的常用术语，表明拉动绳索自由端能够很容易解开绳结。打滑的反手结是这种结中最简单的，常叫做滑结或活结，虽然这是含义宽泛的术语。在历史上，这种简单的绳结用于诱捕鸟类和其他小动物。它也可以被用作可以快速解开的止索结。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k024.jpg"
  },
  {
    "id": "k025",
    "name": "络头结",
    "english": "Perfection Loop；Angler's Loop",
    "alias": "完美环",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "络头结是一种可形成固定绳环的绳结，常和鱼线一起使用。它非常安全但是不容易解开。此结可以系在绳圈中意味着无需使用绳端就可以在绳子中段打结。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k025.jpg"
  },
  {
    "id": "k026",
    "name": "哥萨克结",
    "english": "Inuit Bowline；Sitka Loop；Cossack Knot；Anti-Bowline；Boas Bowline",
    "alias": "爱斯基摩称人结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "哥萨克结比普通的称人结更安全，特别是用于合成线上和线环被拉紧的时候。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k026.jpg"
  },
  {
    "id": "k027",
    "name": "称人结",
    "english": "Bowline；Boling Knot；Bowline Knot；Standing Bowline",
    "alias": "帆索结；布林结；单套结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "称人结用于在绳端形成一个固定的绳环。称人结通常用于航海，也可用于系绑轻型飞机。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k027.jpg"
  },
  {
    "id": "k028",
    "name": "称人结（荷兰）",
    "english": "Cowboy Bowline；Left-hand Bowline；Dutch Bowline；Dutch Marine Bowline；Winter Bowline",
    "alias": "",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "称人结用于在绳端形成一个固定的绳环。称人结是著名的救援结，用于援救从悬崖坠到岩架或坠入洞中的人员。称人结通常用于航海，也可用于系绑轻型飞机。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k028.jpg"
  },
  {
    "id": "k029",
    "name": "称人结（快速）",
    "english": "Snap Bowline；Quick Bowline；Bowline；Boling Knot；Bowline Knot；Standing Bowline",
    "alias": "称人结；帆索结；布林结；单套结",
    "category": "圈结/套结",
    "categoryId": "cat_01",
    "usage": "称人结用于在绳端形成一个固定的绳环。称人结通常用于航海，也可用于系绑轻型飞机。",
    "feature": "属于“圈结/套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k029.jpg"
  },
  {
    "id": "k030",
    "name": "圆周编结",
    "english": "Round Lashing；Vertical Lashing",
    "alias": "",
    "category": "编结",
    "categoryId": "cat_02",
    "usage": "圆周编结用于将系绑两根较短的圆杆形成一根较长的圆杆。通常会将两个圆周编结串联起来使用，通过移动单一圆周编结的固有支点来提高延长圆杆的稳定性。两个编结的距离越远，形成的圆杆就越稳定。",
    "feature": "属于“编结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k030.jpg"
  },
  {
    "id": "k031",
    "name": "三脚架编结",
    "english": "Tripod Lashing；Tripod Lashing with Plain Turns",
    "alias": "三角支架结",
    "category": "编结",
    "categoryId": "cat_02",
    "usage": "三脚架编结用于制作三脚架，是很多营地改良及创新结构的基础。用于例如像脸盆或悬挂提灯这样的营地小工具。在2个三脚架搭配一根圆材可以用作毛巾架。大型项目将三脚架作为建筑模块用于桥梁或塔台。",
    "feature": "属于“编结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k031.jpg"
  },
  {
    "id": "k032",
    "name": "横梁结",
    "english": "Transom Knot",
    "alias": "",
    "category": "编结",
    "categoryId": "cat_02",
    "usage": "横梁结在袋口结的基础上转变而来的，它打结方法很简单，主要用来固定两个互成直角的长线型物体。比如在绑风筝棍子时便可使用这种绳结。",
    "feature": "属于“编结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k032.jpg"
  },
  {
    "id": "k033",
    "name": "十字编结",
    "english": "Diagonal Lashing",
    "alias": "十字结",
    "category": "编结",
    "categoryId": "cat_02",
    "usage": "十字编结是将帆桅杆或杆子捆在一起的编结类型。它通常用于杆子最初接触不到的交叉支撑，但是也可用于45°至90°角相互交叉的任何杆子。大型半永久结构可以采用四方编结（更为牢固）和十字编结的组合。",
    "feature": "属于“编结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k033.jpg"
  },
  {
    "id": "k034",
    "name": "剪立编结",
    "english": "Shear Lashing；Sheer Lashing",
    "alias": "展立结",
    "category": "编结",
    "categoryId": "cat_02",
    "usage": "剪立编结在两个圆杆或圆柱的顶部形成一个支点，如此可以分开圆杆形成支腿。一系列支腿可以构成一座空中桥梁。一套支腿可以作为绳索或其他圆杆的支点，形成一个杠杆。",
    "feature": "属于“编结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k034.jpg"
  },
  {
    "id": "k035",
    "name": "西南部拉编结",
    "english": "West Country Lashing；West Country Round Lashing；West Country Sheer Lashing；West Country Shear Lashing",
    "alias": "长杆结",
    "category": "编结",
    "categoryId": "cat_02",
    "usage": "西南部拉绳结是构建长杆的绝佳选择，例如旗杆。",
    "feature": "属于“编结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k035.jpg"
  },
  {
    "id": "k036",
    "name": "林地扎带编结",
    "english": "Woodland Zip-tie Lashing",
    "alias": "",
    "category": "编结",
    "categoryId": "cat_02",
    "usage": "暂无用途说明，可后续补充。",
    "feature": "属于“编结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k036.jpg"
  },
  {
    "id": "k037",
    "name": "四方编结",
    "english": "Square Lashing",
    "alias": "方回结",
    "category": "编结",
    "categoryId": "cat_02",
    "usage": "四方编结是一种用于捆绑两根杆子的编结。大型结构可以采用四方编结和十字编结的组合，其中四方编结通常用作承载部分，十字编结用于交叉支撑。如果两根杆子间存在空隙，则应该使用十字编结。",
    "feature": "属于“编结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k037.jpg"
  },
  {
    "id": "k038",
    "name": "日本四方编结",
    "english": "Japanese Square Lashing（MKII）；Mark II Square Lashing；Japanese Mark II Square Lashing",
    "alias": "",
    "category": "编结",
    "categoryId": "cat_02",
    "usage": "日本四方编结是传统四方编结的一种替代方式。其主要优点是，它可比传统四方编结系得更快，因为绳子两端可以同时操作。",
    "feature": "属于“编结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k038.jpg"
  },
  {
    "id": "k039",
    "name": "万字结",
    "english": "Sailor's Cross；Southern Cross；Shamrock Knot；True Lover's Knot；Wing Knot；Suavastika",
    "alias": "水手结；三环结；卍字结",
    "category": "多圈结",
    "categoryId": "cat_03",
    "usage": "万字结或同心结（众多名称之一）是一个装饰性的绳结，可以绑在挂带上，并且广泛用在中国编结技术中。",
    "feature": "属于“多圈结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k039.jpg"
  },
  {
    "id": "k040",
    "name": "三套称人结",
    "english": "Triple Bowline；Three Loop Bowline",
    "alias": "",
    "category": "多圈结",
    "categoryId": "cat_03",
    "usage": "三套称人结用于在绳索中间形成三个固定环，可以在不接触末端得情况下进行捆扎。",
    "feature": "属于“多圈结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k040.jpg"
  },
  {
    "id": "k041",
    "name": "桅顶结",
    "english": "Jury Mast Knot；Masthead Knot；Pitcher Knot",
    "alias": "旗杆结",
    "category": "多圈结",
    "categoryId": "cat_03",
    "usage": "桅顶结通常用作帆船或船只上原配桅杆缺失，操作临时桅杆的工具。该结位于新桅杆的顶部，桅杆穿过绳结的中心。绳结的套结则用作锚点。通常会在新桅杆上附加小块的木头或者刻槽，避免绳结下滑。如今，该结多作为垫子底部的装饰性绳结。",
    "feature": "属于“多圈结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k041.jpg"
  },
  {
    "id": "k042",
    "name": "手铐结",
    "english": "Handcuff Knot；Hobble Knot",
    "alias": "",
    "category": "多圈结",
    "categoryId": "cat_03",
    "usage": "手铐结系在绳子中间，形成两个可调的绳环，可以绕双手或双脚收紧。该结本身不具有任何内在的锁紧能力，因此并不如名字所说的那样好用。在某些救援情况下，手铐结可用于将人员拉出没有足够空间使用救援安全带或其他此类装置的狭小空间。",
    "feature": "属于“多圈结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k042.jpg"
  },
  {
    "id": "k043",
    "name": "兔耳结",
    "english": "Double Bight Figure Eight；Bunny Ears；Y-Hang；Double Figure 8 Loop；Double Loop Figure Eight；Double Flemish Loop；Canadian Eight；Canadian Figure 8",
    "alias": "双股的八字结",
    "category": "多圈结",
    "categoryId": "cat_03",
    "usage": "兔耳结常用于在攀岩时平衡二个地锚，还可以提供冗余度。与其他许多双环绳结相比，兔耳结牢固安全，将绳子从一环移向另一环就可以轻松容易地调整绳环大小。每个绳环分摊约50%的载荷。若任意绳环、任意地锚或任意登山扣受损，则不能勉强使用其余的地锚组合。",
    "feature": "属于“多圈结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k043.jpg"
  },
  {
    "id": "k044",
    "name": "葡萄牙称人结",
    "english": "Portuguese Bowline；French Bowline；Equalizing Bowline",
    "alias": "",
    "category": "多圈结",
    "categoryId": "cat_03",
    "usage": "葡萄牙称人结是称人结的一种变形，设有两个圆环，且可大可小。",
    "feature": "属于“多圈结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k044.jpg"
  },
  {
    "id": "k045",
    "name": "西班牙称人结",
    "english": "Spanish Bowline",
    "alias": "",
    "category": "多圈结",
    "categoryId": "cat_03",
    "usage": "西班牙称人结是可用于将人托起的一种双环结。",
    "feature": "属于“多圈结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k045.jpg"
  },
  {
    "id": "k046",
    "name": "消防员椅结",
    "english": "Fireman's Chair；Chair Knot；Man-o-War Sheepshank",
    "alias": "椅结",
    "category": "多圈结",
    "categoryId": "cat_03",
    "usage": "消防员椅结是一种系在绳子中央，形成两个可调式锁紧绳环的绳结。该绳结由专业人士采用合适的绳索结成；当下放人员到安全地带时，可以用作支撑人员的救援安全带。一个绳环支撑身体，穿过臂下环绕胸部，另一绳环在膝下支撑腿部。消防员椅结由一个手扣结，绕各绳环的一个锁紧半扣结组成。绳环大小可以进行调整，直至半扣结锁紧为止。",
    "feature": "属于“多圈结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k046.jpg"
  },
  {
    "id": "k047",
    "name": "鞋带结",
    "english": "Bow Knot；Shoelace Knot；Slipped Reef Knot；Slipped Square Knot",
    "alias": "蝴蝶结",
    "category": "多圈结",
    "categoryId": "cat_03",
    "usage": "鞋带结通常用来系鞋带，打结和解开都很容易。",
    "feature": "属于“多圈结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k047.jpg"
  },
  {
    "id": "k048",
    "name": "双称人结",
    "english": "Bowline on a Bight；Bosun's Chair；Y-Hang；Bowline upon the Bight；Two Loop Bowline",
    "alias": "",
    "category": "多圈结",
    "categoryId": "cat_03",
    "usage": "双称人结是绳索中央有一对大小固定绳环的结子。它的优点是绳环不会滑脱，张紧后较容易解开。急救时，双称人结可用作提升椅。当需要一个牢固的绳环但是无法接触任意绳端时，该结是很方便的。",
    "feature": "属于“多圈结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k048.jpg"
  },
  {
    "id": "k049",
    "name": "双称人结（2）",
    "english": "Rethreaded Bowline；Retraced Bowline；Bowline on a Bight；Bowline Follow Thru；Bowline upon the Bight",
    "alias": "",
    "category": "多圈结",
    "categoryId": "cat_03",
    "usage": "双称人结是绳索中央有一对大小固定绳环的结子。它的优点是绳环不会滑脱，张紧后较容易解开。急救时，双称人结可用作提升椅。",
    "feature": "属于“多圈结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k049.jpg"
  },
  {
    "id": "k050",
    "name": "布莱克氏结",
    "english": "Blake's Hitch",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "布莱克氏结一般是树艺师和攀登树木者用来在攀爬时使用的摩擦绳结。其它普通的攀爬绳结一般会使用绳索圈，布莱克氏结则不同，它用绳索的尾部做成。尽管本身已经很牢固，但是为了安全起见，还是建议绑一个绳尾结如 八字结 以便巩固一下（动画里没有展示）。上下攀爬都能用得上，很多树艺师都更喜欢使用这类绳结，因为它不太会缠绕在一起。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k050.jpg"
  },
  {
    "id": "k051",
    "name": "帆脚索",
    "english": "Buntline Hitch；Inside Clove Hitch；Studding Sail Tack Bend",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "帆脚结是用于将绳索捆绑到环状物、吊眼、杆子、鱼竿和栏杆上等需要牢固绳结之处的结子。从结构上说，帆脚结与双半结类似。当结子受力过大时，可能解开困难或无法解开。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k051.jpg"
  },
  {
    "id": "k052",
    "name": "帆索滑结",
    "english": "Slipped Buntline Hitch；Quick Release Buntline",
    "alias": "快解帆索结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "帆索滑结用于将绳索连接到需要安全结扣但仍可快速轻松地解开的圆环、柱子或栏杆上。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k052.jpg"
  },
  {
    "id": "k053",
    "name": "帆杆结",
    "english": "Boom Hitch",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "这种绳结是一种将绳索连接到管道或立柱等固定圆柱形物体上的安全方法，适用于平行拉力和直角拉力应用。无论是湿绳索还是干绳索，均同样适用。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k053.jpg"
  },
  {
    "id": "k054",
    "name": "三套结",
    "english": "Rolling Hitch；Midshipman's Hitch",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "三套结是将绳索固定到鱼竿、杆子或其他绳索的绳结。它是个简单的摩擦结，常用于平行沿物体牵拉，而不是以直角形式牵拉。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k054.jpg"
  },
  {
    "id": "k055",
    "name": "吊桶结",
    "english": "Barrel Hitch",
    "alias": "桶结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "吊桶结用于在船上起重货物，是一种极有效率的悬挂圆柱形物体的方法，例如圆筒或水桶。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k055.jpg"
  },
  {
    "id": "k056",
    "name": "吊床结",
    "english": "Becket Hitch（Slipped）；Hammock Knot；Quick Release Becket Hitch",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "吊床结在吊床露营社区很流行，因为它结绳的速度快而且绑和解绑简单。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k056.jpg"
  },
  {
    "id": "k057",
    "name": "帕洛玛结",
    "english": "Palomar Knot",
    "alias": "帕洛马结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "帕洛玛结用于将鱼线固定到鱼饵，扣环或转环上。它与其他紧固用具同样有效（例如，狗夹的绳子），而被绑的物体可以穿过绳环，并且绳线或绳索不能太粗。通过实践发现，黑暗中使用冰冷的手即可打结。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k057.jpg"
  },
  {
    "id": "k058",
    "name": "锚结",
    "english": "Anchor Hitch；Anchor Bend；Fisherman's Hitch；Fisherman's Bend",
    "alias": "渔人结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "锚结用于将绳子系在环状物体上。它是系锚或者系锚链公认的绳结。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k058.jpg"
  },
  {
    "id": "k059",
    "name": "贝克特结",
    "english": "Becket Hitch；Becket Hitch Proper",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "暂无用途说明，可后续补充。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k059.jpg"
  },
  {
    "id": "k060",
    "name": "营钉结",
    "english": "Taut-line Hitch；Tent-line Hitch；Rigger's Hitch；Adjustable Hitch",
    "alias": "紧绳结；拉钩结；拉绳结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "营钉结是一种用于绳子受拉下的可调节的环结。当一段绳索需要定期调整来维持绳子的张力时，通常使用该绳结。滑动结套调整绳环大小就可以维持绳子张力，因而可以改变绳子的有效长度而无需重新打结。绳结通常用在户外活动如露营中固定帐篷绳，由树艺师爬树时使用，在潮汐区域建立可调节的系泊点，以及固定车上的货物。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k060.jpg"
  },
  {
    "id": "k061",
    "name": "天线袋口滑结",
    "english": "Slipped Ground-line Hitch；Slipped Spar Hitch；Fender Knot；Miller's Knot；Sack Knot；Bag Knot",
    "alias": "基线套钩滑结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "这种绳结可以用来将绳索临时系于立柱上。它也可以用来捆绑包袋的开口，解开也很快速简便。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k061.jpg"
  },
  {
    "id": "k062",
    "name": "天线袋口结",
    "english": "Ground-line Hitch；Spar Hitch；Picket-line Hitch；Fender Knot；Miller's Knot；Sack Knot；Bag Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "这种绳结可以用来把绳索系在立柱上，或者把细绳系在粗绳上。在划船和帆船应用中，该绳结用于将物体系在栏杆之上。它也可以用来栓马。这种绳结还可以用来扎紧包袋的开口，通常可以快速松解，使内容物易于拿取。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k062.jpg"
  },
  {
    "id": "k063",
    "name": "戴维结",
    "english": "Davy Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "在飞绳钓用户中很受欢迎，戴维结可以简单快速的打好。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k063.jpg"
  },
  {
    "id": "k064",
    "name": "改进的扭抱",
    "english": "Clinch Knot（Improved）",
    "alias": "改进的克林奇结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "改进的扭抱结用于将鱼线固定在鱼饵上，还能在鱼线上固定转环，夹子或者人工苍蝇。改进的扭抱结在渔夫中非常流行，因为它不仅牢固，而且便于打结。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k064.jpg"
  },
  {
    "id": "k065",
    "name": "活索结",
    "english": "Mooring Hitch",
    "alias": "码头索",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "活索结是一个可快速打开的绳结，用于临时固定小船或小动物。活索结在承重时会快速张紧，但是当拉动自由端时它会瞬间释放。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k065.jpg"
  },
  {
    "id": "k066",
    "name": "DISTEL结",
    "english": "Distel Hitch；4 over 1 Distel",
    "alias": "迪斯特尔绳结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "迪斯特尔绳结作为一种方向性摩擦绳结经常被园艺师所使用。也常用于将登山用铁锁系到绳索上，以供登山者上升或下降时使用。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k066.jpg"
  },
  {
    "id": "k067",
    "name": "𢃇缆结",
    "english": "Halyard Hitch；Jeanneau Halyard Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "缆结是用于航海的一种紧凑绳结，将绳子系于钩链或钩环。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k067.jpg"
  },
  {
    "id": "k068",
    "name": "半扣结",
    "english": "Half Hitch；Single Hitch",
    "alias": "半结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "半扣结是简单的反手结的变种。绳结本身并不牢固，但它是各种有用且可靠的套结、绳套和绳结的重要组成部分。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k068.jpg"
  },
  {
    "id": "k069",
    "name": "克式抓结",
    "english": "Klemheist；French Machard Knot；Kleimheist（common misspelling）",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "克氏抓结是一种摩擦力绳结，当施力时收紧绳索，重量释放时可以自由移动。它用于登山绳索的上升与下降，与普鲁士结相似。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k069.jpg"
  },
  {
    "id": "k070",
    "name": "克雷圆环结",
    "english": "Kreh Loop；Non-Slip Mono Knot；Lefty Kreh's Loop Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "克雷圆环结用于飞绳钓鱼，将鱼线连至假绳或鱼饵。由于固定的圆环结未抓牢鱼饵，因此可呈现出更自然的动作。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k070.jpg"
  },
  {
    "id": "k071",
    "name": "MAGNUS 结",
    "english": "Magnus Hitch；Magner's Hitch；Taut-line Hitch",
    "alias": "马格努斯结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "暂无用途说明，可后续补充。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k071.jpg"
  },
  {
    "id": "k072",
    "name": "MIDSHIPMAN 结",
    "english": "Midshipman's Hitch；Rolling Hitch；Taut-line Hitch",
    "alias": "三套结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "MIDSHIPMAN结是一种用于绳子受拉下的可调节的环结。当一段绳索需要定期调整来维持绳子的张力时，通常使用该绳结。滑动结套调整绳环大小就可以维持绳子张力，因而可以改变绳子的有效长度而无需重新打结。绳结通常用在户外活动如露营中固定帐篷绳，由树艺师爬树时使用，在潮汐区域建立可调节的系泊点，以及固定车上的货物。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k072.jpg"
  },
  {
    "id": "k073",
    "name": "ORVIS 结",
    "english": "Orvis Knot；Becker Knot",
    "alias": "奥维斯结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "奥维斯结是一种结实，易于打结，打在钩上的钩鱼结。它是改进的克林奇结的一个很好的另一个选择。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k073.jpg"
  },
  {
    "id": "k074",
    "name": "RAPALA 结",
    "english": "Rapala Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "RAPALA 结常用于钓鱼，是一个绳端环结，用于固定诱饵或者需要自由、自然运动的苍蝇。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k074.jpg"
  },
  {
    "id": "k075",
    "name": "SAN DIEGO JAM 结",
    "english": "San Diego Jam；Reverse Clinch Knot；Heiliger Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "SAN DIEGO JAM结常用于钓鱼，是固定鱼饵或苍蝇的最结实的绳端结之一。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k075.jpg"
  },
  {
    "id": "k076",
    "name": "SCHWABISCH 结",
    "english": "Schwabisch；Asymmetric Prusik；Schwabisch Hitch；Schwabisch Prusik；Schwabish；Schwabisch",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "Schwabisch结是一种方向性摩擦绳结，在园艺师中非常流行。也用于登山用铁索和绳索的绑定，使登山者上可以升或下降。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k076.jpg"
  },
  {
    "id": "k077",
    "name": "TRILENE 结",
    "english": "Trilene Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "TRILENE 结是一种多功能的钓鱼结，可以连接细线和鱼钩、转环与鱼饵。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k077.jpg"
  },
  {
    "id": "k078",
    "name": "单环结",
    "english": "Munter Hitch；Italian Hitch；Crossing Hitch；HMS；Tag Knot；MB",
    "alias": "意大利半结；意大利半扣；HMS",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "单环结是一个简单的绳结，常被登山者或洞穴探险者用作救生索或栓绳系统的一部分。此项技术可以配合任何足够拧两圈绳子宽的登山扣使用。单环结通过在绳子之间和它所缠绕的物体上形成摩擦来产生摩擦力。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k078.jpg"
  },
  {
    "id": "k079",
    "name": "VALDOTAIN 结",
    "english": "Valdotain Tresse；VT；Vallard Tresse；VAldotain Tresse",
    "alias": "维尔德特恩织结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "维尔德特恩织结是一种在园艺师中流行的方向性摩擦绳结。也常用于将登山用铁锁系到绳索上，以供登山者上升或下降时使用。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k079.jpg"
  },
  {
    "id": "k080",
    "name": "牛索结",
    "english": "Cow Hitch；Lark's Head；Lark's Foot；Reverse Double Half Hitch；Double Stitch；Girth Hitch；Deadeye Hitch",
    "alias": "雀头结；双合结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "牛索结是将动物拴在杆子上的简单绳结。结好后，牛索结的结构与雀头结一致。只是捆绑方式上有所不同。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k080.jpg"
  },
  {
    "id": "k081",
    "name": "车伕结",
    "english": "Truckie Hitch；Dolly Knot；Waggoner's Hitch；Lorry Driver's Hitch；Wakos Transport Knot；Sheepshark Style Trucker's Hitch",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "车夫结，传统上被用来把运载的货物固定在货车、卡车和拖车上。这种车夫结的变体在日本和澳大利亚非常流行，本质上比那些使用固定绳圈的变体更具有临时性，而且更能容易和更快地将其解开。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k081.jpg"
  },
  {
    "id": "k082",
    "name": "车夫结",
    "english": "Trucker's Hitch；Lorry Driver's Hitch；Harvester's Hitch；Hay Knot；Wagoner's Hitch；Power Cinch",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "车夫结的第一部分由蝴蝶环结构成。单独查看蝴蝶结部分，了解它是如何打结的。 车夫结是一种复合（多部分）结，通常用于固定货车或拖车上的货物。长期以来，该结一直用作张力线索，因名称众多而著名。据说，车夫结可以追溯到马车夫和小贩使用马拉货车运送货物的日子。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k082.jpg"
  },
  {
    "id": "k083",
    "name": "桩结",
    "english": "Pile Hitch",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "桩结被用来把系船索套在码头杆或系船桩上。此绳结很容易绑，可以绑成绳圈，绳圈不会靠近绳子的两端。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k083.jpg"
  },
  {
    "id": "k084",
    "name": "八字返穿结",
    "english": "Figure Eight Follow Through；Figure Eight Retrace；Rerouted Figure Eight Loop；Threaded Figure Eight Loop",
    "alias": "穿式八字结；翻穿双八字结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "八字返穿结常用于攀岩和洞穴探险（绳子张力中等），用于在绳子端部或环绕物体形成一个固定的绳环。它解开相对容易并且牢固，但是重载后会变得难以解开。当绳结必须系在无法轻易套上绳环的物体时，可使用“重新编结”的方法。特别的，它可用于将绳子系在攀岩安全带上。双环称人结可以完成同样的任务，打结更快并且不会死结，但是对于初学者来说，八字返穿结更容易上手，可快速检查打结是否正确。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k084.jpg"
  },
  {
    "id": "k085",
    "name": "马贼索",
    "english": "Highwayman's Hitch；Highwayman's Cutaway；Dick Turpin's Knot；Highwayman's Getaway；Boat Hitch；Draw Hitch",
    "alias": "牧童结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "马贼索 能很快解开，一般是临时要固定一根绳索，之后又需要能轻松地全部解开时使用。这种绳结在工作端用力一拉便可解开。通常被用来临时性地把动物或船只固定在竿子旁。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k085.jpg"
  },
  {
    "id": "k086",
    "name": "普鲁士抓结",
    "english": "Prusik；Prusik Hitch；Middle of the Rope Prusik",
    "alias": "普鲁士结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "普鲁士抓结是一个摩擦结，用于绕绳索结成一圈绳环，应用于攀岩，峡谷漂流，登山，洞穴探险，绳索救援以及树艺家使用。普鲁士抓结以其发明者奥地利登山家卡尔普鲁士博士的名字命名。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k086.jpg"
  },
  {
    "id": "k087",
    "name": "普鲁士结（绳尾）",
    "english": "Prusik（End-line）；Prusik Hitch；End of the Rope Prusik；End-line Prusik",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "这种可移动德绳结可以系在绳索的末端，将一根绳索连接到另一根绳索上。也可以用来把绳索系在立柱上。它主要用于攀爬应用，末尾应使用安全结。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k087.jpg"
  },
  {
    "id": "k088",
    "name": "轱辘结",
    "english": "Arbor Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "轱辘结主要用来将鱼线绑到绕线轮的轱辘上。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k088.jpg"
  },
  {
    "id": "k089",
    "name": "驳船结",
    "english": "Lighterman's Hitch；Tugboat Hitch；Canalman's Hitch；Backhand Mooring Hitch",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "驳船结是将船临时系到系揽柱上的一种快速方法。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k089.jpg"
  },
  {
    "id": "k090",
    "name": "西伯利亚套结",
    "english": "Siberian Hitch；Evenk Knot",
    "alias": "鄂温克结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "西伯利亚套结被用来把绳子系在一个物体上。该绳结捆绑起来很方便，即使在寒冷的天气情况下，戴了厚厚的分指或连指手套都可以打结。作为一个活结，它可以很快解开，只需拉一下该绳索的工作端即可。西伯利亚套结适合一般的、非重要的场合，比如，固定防水布的绷绳。它不适合要求比较高的情况。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k090.jpg"
  },
  {
    "id": "k091",
    "name": "内跨结",
    "english": "Snell Knot；Snood Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "内跨结被用来把有眼的鱼钩系在钓鱼线上。绑了内跨结的鱼钩可以方便人们均匀地、直线型的拉动鱼。这根线穿过鱼钩的洞眼，但是主要还是系在鱼竿上。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k091.jpg"
  },
  {
    "id": "k092",
    "name": "超级单环结",
    "english": "Super Munter；Monster Munter；Double Munter；Zigzag Knot",
    "alias": "超级意大利半结；超级意大利半扣",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "这种绳结通常在救援场景中使用，用于放低重物。在标准单环结（Munter Hitch）上增加的翻转环会产生更多的摩擦力，并减少控制下降所需的力。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k092.jpg"
  },
  {
    "id": "k093",
    "name": "羊角结",
    "english": "Cleat Hitch；Cleat Knot",
    "alias": "磁夹板结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "羊角结用于将绳索绑在系缆墩上。几乎所有船只的首部和尾部都有系缆墩。系缆墩还常见于船坞。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k093.jpg"
  },
  {
    "id": "k094",
    "name": "邓肯环",
    "english": "Uni Knot；Duncan Loop；Grinner Knot",
    "alias": "万能结；露齿结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "邓肯环是一种多用途的钓鱼结，可将鱼线连接到绕线筒轴上，用于连接线索，以及固定诱饵，卡环以及转环到线索端部。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k094.jpg"
  },
  {
    "id": "k095",
    "name": "蒙特牵引结",
    "english": "Munter Mule；Munter Mule Overhand；MMO",
    "alias": "用单结锁定的意大利驴耳结；意大利半结-骡耳结组合结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "这种组合结用于索降，而且可以松懈，甚至在拉紧的情况下也可以解开。这种攀爬结用于固定单环结（Munter Hitch），有时被称为救援者的“第三只手”。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k095.jpg"
  },
  {
    "id": "k096",
    "name": "钩孔结",
    "english": "Turler Knot；Major Turle's Knot；Turtle Knot；Turrel Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "钩孔结用于将角或钩假蝇系于鱼线。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k096.jpg"
  },
  {
    "id": "k097",
    "name": "钩结",
    "english": "Cat's Paw",
    "alias": "猫爪结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "钩结通常用于将一段绳索与环子或钩子之类的物品相连。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k097.jpg"
  },
  {
    "id": "k098",
    "name": "皮岑结",
    "english": "Pitzen Knot；Eugene Bend；16-20 Knot；Sixteen-Twenty Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "皮岑结是一种最结实的结，用来系诱饵，钓钩或钓鱼线。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k098.jpg"
  },
  {
    "id": "k099",
    "name": "冰柱结",
    "english": "Icicle Hitch",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "冰柱结是当绳端重量沿指定方向并平行于杆子施加时与杆子相连的优秀绳结。当绳结在光滑表面承受巨大载荷时，绳结仍能保持原位。该结甚至可以悬挂在锥形的杆子上（因而得名“冰柱结”）。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k099.jpg"
  },
  {
    "id": "k100",
    "name": "雀头结",
    "english": "Lanyard Hitch；Girth Hitch；Ring Hitch；Lark's Head；Bale Sling Hitch；Baggage Tag Loop；Tag Knot",
    "alias": "系物结；挂绳栓",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "雀头结通常用于将一小段绳索连接到带孔的物体上，如姓名牌或者口哨。雀头结还可用于将一小段绳子连接到帐篷或陷阱上的环子或者扣眼上。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k100.jpg"
  },
  {
    "id": "k101",
    "name": "秋千结",
    "english": "Swing Hitch；Rope Swing Knot；Tire Swing Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "秋千结用于将秋千的绳子系在圆木杆或树枝上。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k101.jpg"
  },
  {
    "id": "k102",
    "name": "双戴维结",
    "english": "Double Davy",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "在飞蝇钓用户中很受欢迎，戴维结可以简单快速的打好。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k102.jpg"
  },
  {
    "id": "k103",
    "name": "双半结",
    "english": "Two Half Hitches；Clove Hitch Over Itself",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "双半结是一种通用结。它通常用于系绑绳索，与杆子或环状物呈垂直拉伸状。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k103.jpg"
  },
  {
    "id": "k104",
    "name": "双套滑结",
    "english": "Slipped Clove Hitch；Quick Release Clove Hitch；Slippery Hitch",
    "alias": "快解双套结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "双套滑结用于将绳索临时连接到柱子或栏杆上，可以快速轻松地解开。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k104.jpg"
  },
  {
    "id": "k105",
    "name": "双套结",
    "english": "Clove Hitch on a Bight；Builder's Knot；Clove Hitch in the Bight",
    "alias": "丁香结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "这个方法展示如何快速便捷的使用双套结将绳索捆绑到棍子或杆子上，如果没使用在绳子的末端，它的作用有限。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k105.jpg"
  },
  {
    "id": "k106",
    "name": "双套结",
    "english": "Clove Hitch（Two Loops）；Builder's Knot；Clove Hitch in the Bight",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "暂无用途说明，可后续补充。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k106.jpg"
  },
  {
    "id": "k107",
    "name": "双套结",
    "english": "Clove Hitch；Builder's Knot",
    "alias": "酒瓶结；斜卷结；卷结；丁香结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "双套结通常用在开始和结束一段编结之前，如四方编结、十字编结和剪立编结。许多人认为该结是一个“必要”的绳结。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k107.jpg"
  },
  {
    "id": "k108",
    "name": "反手结",
    "english": "Backhand Hitch；High Tie；High Safety Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "反手结通常在固定运送荷载时被用作锚。当绳索受力时，反手结很容易解开。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k108.jpg"
  },
  {
    "id": "k109",
    "name": "滑收缩结",
    "english": "Slipped Constrictor Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "收缩结是最有效的捆绑结之一。它简单、牢固，一旦系紧后很难或者不可能解开。收缩结适合于需要临时固定或者半永久绑定的情况。收缩结当作软管夹或者电缆夹也很好用。这种绳结是收缩结（Constrictor knot）的快速松解版本。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k109.jpg"
  },
  {
    "id": "k110",
    "name": "滑接绳结",
    "english": "Tiller's Hitch；Slipped Sheet Bend；Quick Release Sheet Bend；Slipped Becket Bend",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "滑接绳结是快速解结的接绳结。历史上，该结曾被用作固定一条船上抽屉的临时绳结。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k110.jpg"
  },
  {
    "id": "k111",
    "name": "法里蒙摩擦结",
    "english": "Farrimond Friction Hitch",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "法里蒙摩擦结是一种用于绳索受拉状态下使用的可快速释放、可调节摩擦绳结。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k111.jpg"
  },
  {
    "id": "k112",
    "name": "他拔结",
    "english": "Tarbuck",
    "alias": "TARBUCK 结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "很有用的滑动抓取线环，他拔结是一种摩擦结，可在松弛的时候轻松地在绳子上上下移动——而且在负载情况下，此结仍然很结实！这种结通常在营地环境中用来调整帐篷绳子、吊床和防水布。虽然最初设计为攀登结，但使用在现代攀岩绳上并不安全。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k112.jpg"
  },
  {
    "id": "k113",
    "name": "无张力结",
    "english": "Tensionless Hitch；No-Knot",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "无张力结，配上合适的锚点，可以成为最牢固的锚索。因为无需打结，所以系绑绳索很快。此结的受拉能力取决于缠绕的圈数，表面摩擦和树木、柱子、岩石或杆子的直径。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k113.jpg"
  },
  {
    "id": "k114",
    "name": "波尔多滑轮结",
    "english": "Poldo Tackle",
    "alias": "波尔多索结；波尔多系统",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "波尔多滑轮结是一种高度通用、可调节的紧张系统，专为快速收紧或松开而设计。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k114.jpg"
  },
  {
    "id": "k115",
    "name": "巫毒结",
    "english": "Voodoo Hitch；Transport Hitch；PM Hitch（Pure Magic）",
    "alias": "巫毒系统；运输结；巫毒滑轮结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "巫毒结，亦称运输结，是一种卓越的紧张系统。它提供一种简易的方法，向固定绳索增加易于调节的张力。巫毒结广泛应用于各个领域，包括激流救援。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k115.jpg"
  },
  {
    "id": "k116",
    "name": "快速连接结",
    "english": "Quick Hitch；Slipped Lapp Knot",
    "alias": "速套结；滑拉普结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "这种绳结通常由树艺师使用，是拉起第二根绳索的简单快捷的方法。也很容易快速解开。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k116.jpg"
  },
  {
    "id": "k117",
    "name": "可调节绳结",
    "english": "Adjustable Grip Hitch；Adjustable Loop；Cawley Adjustable Hitch",
    "alias": "",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "可调节绳结 是个简单有用的摩擦结，如果绳结系得较松，便可轻松地上下调节绳结在绳索上的位置---然而如果在绳结上挂上物体，那么绳结就会收紧而变得牢固！这种绳结用途广泛，可以满足多种需求，但主要还是在搭帐篷时使用，因为它可用来调节帐篷的边线，吊床及防水布。若要在光滑材质上增加摩擦力以及“握力”，还可以加一些绳头结。而且，它不能用在攀岩上，因为冲击力增加之后有可能会打滑。可调节绳结 可用来代替 营钉结 ---一般来说效果都会更好！",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k117.jpg"
  },
  {
    "id": "k118",
    "name": "石锚结",
    "english": "Killick Hitch；Kelleg Hitch",
    "alias": "圆材结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "石锚结用于将一根绳索绑在木头上，以便牵引或提升。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k118.jpg"
  },
  {
    "id": "k119",
    "name": "绳针结",
    "english": "Marlinspike Hitch；Marlingspike Hitch；Boat Knot；Rope Ladder Knot",
    "alias": "索针结；绳梯结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "绳针结是一种安全的临时性绳结，可以通过移除栓扣轻松的释放。如果绳索需要加力，可以将它临时绑定在绳索上，这是一种非常好的方法。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k119.jpg"
  },
  {
    "id": "k120",
    "name": "系木结",
    "english": "Timber Hitch；Bowyer's Knot；Lumberman's Knot；Countryman's Knot",
    "alias": "圆材结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "系木结用于将一根绳索绑在木头上，以便牵引或提升。它还是十字编结的起始结。还用它将弓弦端部与英国长弓的下缘相连。另外的用途是将琴弦连接到四弦琴和古典木吉他的琴桥。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k120.jpg"
  },
  {
    "id": "k121",
    "name": "系木结",
    "english": "Round Turn & Two Half Hitches",
    "alias": "旋圆双半结；旋圆两半结",
    "category": "套结",
    "categoryId": "cat_04",
    "usage": "系木结是将绳端固定在固定物体上的绳结，常用于将船只系泊在永久的桩体，系泊点，栏杆或环状物上。",
    "feature": "属于“套结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k121.jpg"
  },
  {
    "id": "k122",
    "name": "布莱克氏结",
    "english": "Blake's Hitch",
    "alias": "",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "布莱克氏结 一般是树艺师和攀登树木者用来在攀爬时使用的摩擦绳结。其它普通的攀爬绳结一般会使用绳索圈， 布莱克氏结 则不同，它用绳索的尾部做成。尽管本身已经很牢固，但是为了安全起见，还是建议绑一个绳尾结如 八字结 以便巩固一下（动画里没有展示）。上下攀爬都能用得上，很多树艺师都更喜欢使用这类绳结，因为它不太会缠绕在一起。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k122.jpg"
  },
  {
    "id": "k123",
    "name": "三套结",
    "english": "Rolling Hitch；Midshipman's Hitch",
    "alias": "",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "三套结是将绳索固定到鱼竿、杆子或其他绳索的绳结。它是个简单的摩擦结，常用于平行沿物体牵拉，而不是以直角形式牵拉。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k123.jpg"
  },
  {
    "id": "k124",
    "name": "营钉结",
    "english": "Taut-line Hitch；Tent-line Hitch；Rigger's Hitch；Adjustable Hitch",
    "alias": "紧绳结；连钩结；拉绳结",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "营钉结是一种用于绳子受拉下的可调节的环结。当一段绳索需要定期调整来维持绳子的张力时，通常使用该绳结。滑动结套调整绳环大小就可以维持绳子张力，因而可以改变绳子的有效长度而无需重新打结。绳结通常用在户外活动如露营中固定帐篷绳，由树艺师爬树时使用，在潮汐区域建立可调节的系泊点，以及固定车上的货物。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k124.jpg"
  },
  {
    "id": "k125",
    "name": "DISTEL 结",
    "english": "Distel Hitch；4 over 1 Distel",
    "alias": "迪斯特尔绳结",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "迪斯特尔绳结作为一种方向性摩擦绳结经常被园艺师所使用。也常用于将登山用铁锁系到绳索上，以供登山者上升或下降时使用。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k125.jpg"
  },
  {
    "id": "k126",
    "name": "克式抓结",
    "english": "Klemheist；French Machard Knot；Kleimheist（common misspelling）",
    "alias": "",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "克氏抓结是一种摩擦力绳结，当施力时收紧绳索，重量释放时可以自由移动。它用于登山绳索的上升与下降，与普鲁士结相似。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k126.jpg"
  },
  {
    "id": "k127",
    "name": "MAGNUS 结",
    "english": "Magnus Hitch；Magner's Hitch；Taut-line Hitch",
    "alias": "马格努斯结",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "暂无用途说明，可后续补充。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k127.jpg"
  },
  {
    "id": "k128",
    "name": "MIDSHIPMAN 结",
    "english": "Midshipman's Hitch；Rolling Hitch；Taut-line Hitch",
    "alias": "三套结",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "MIDSHIPMAN结是一种用于绳子受拉下的可调节的环结。当一段绳索需要定期调整来维持绳子的张力时，通常使用该绳结。滑动结套调整绳环大小就可以维持绳子张力，因而可以改变绳子的有效长度而无需重新打结。绳结通常用在户外活动如露营中固定帐篷绳，由树艺师爬树时使用，在潮汐区域建立可调节的系泊点，以及固定车上的货物。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k128.jpg"
  },
  {
    "id": "k129",
    "name": "SCHWABISCH 结",
    "english": "Schwabisch；Asymmetric Prusik；Schwabisch Hitch；Schwabisch Prusik；Schwabish；Schwabisch",
    "alias": "",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "Schwabisch结是一种方向性摩擦绳结，在园艺师中非常流行。也用于登山用铁索和绳索的绑定，使登山者上可以升或下降。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k129.jpg"
  },
  {
    "id": "k130",
    "name": "VALDOTAIN 结",
    "english": "Valdotain Tresse；VT；Vallard Tresse；Valdotain Tresse",
    "alias": "维尔德特恩织结",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "维尔德特恩织结是一种在园艺师中流行的方向性摩擦绳结。也常用于将登山用铁锁系到绳索上，以供登山者上升或下降时使用。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k130.jpg"
  },
  {
    "id": "k131",
    "name": "普鲁士抓结",
    "english": "Prusik；Prusik Hitch；Middle of the Rope Prusik",
    "alias": "普鲁士结",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "普鲁士抓结是一个摩擦结，用于绕绳索结成一圈绳环，应用于攀岩，峡谷漂流，登山，洞穴探险，绳索救援以及树艺家使用。普鲁士抓结以其发明者奥地利登山家卡尔普鲁士博士的名字命名。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k131.jpg"
  },
  {
    "id": "k132",
    "name": "普鲁士结（绳尾）",
    "english": "Prusik（End-line）；Prusik Hitch；End of the Rope Prusik；End-line Prusik",
    "alias": "",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "这种可移动的绳结可以系在绳索的末端，将一根绳索连接到另一根绳索上。也可以用来把绳索系在立柱上。它主要用于攀爬应用，末尾应使用安全结。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k132.jpg"
  },
  {
    "id": "k133",
    "name": "冰柱结",
    "english": "Icicle Hitch",
    "alias": "",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "冰柱结是当绳端重量沿指定方向并平行于杆子施加时与杆子相连的优秀绳结。当绳结在光滑表面承受巨大载荷时，绳结仍能保持原位。该结甚至可以悬挂在锥形的杆子上（因而得名“冰柱结”）。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k133.jpg"
  },
  {
    "id": "k134",
    "name": "法里蒙摩擦结",
    "english": "Farrimond Friction Hitch",
    "alias": "",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "法里蒙摩擦结是一种用于绳索受拉状态下使用的可快速释放、可调节摩擦绳结。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k134.jpg"
  },
  {
    "id": "k135",
    "name": "他拔结",
    "english": "TARBUCK 结",
    "alias": "",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "很有用的滑动抓取线环，他拔结是一种摩擦结，可在松弛的时候轻松地在绳子上上下移动——而且在负载情况下，此结仍然很结实！这种结通常在营地环境中用来调整帐篷绳子、吊床和防水布。虽然最初设计为攀登结，但使用在现代攀岩绳上并不安全。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k135.jpg"
  },
  {
    "id": "k136",
    "name": "可调节绳结",
    "english": "Adjustable Grip Hitch；Adjustable Loop；Cawley Adjustable Hitch",
    "alias": "",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "可调节绳结 是个简单有用的摩擦结，如果绳结系得较松，便可轻松地上下调节绳结在绳索上的位置---然而如果在绳结上挂上物体，那么绳结就会收紧而变得牢固！这种绳结用途广泛，可以满足多种需求，但主要还是在搭帐篷时使用，因为它可用来调节帐篷的边线，吊床及防水布。若要在光滑材质上增加摩擦力以及“握力”，还可以加一些绳头结。而且，它不能用在攀岩上，因为冲击力增加之后有可能会打滑。可调节绳结 可用来代替 营钉结 ---一般来说效果都会更好！",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k136.jpg"
  },
  {
    "id": "k137",
    "name": "波尔多滑轮结",
    "english": "Poldo Tackle",
    "alias": "波尔多索结；波尔多系统",
    "category": "摩擦结",
    "categoryId": "cat_05",
    "usage": "波尔多滑轮结是一种高度通用、可调节的紧张系统，专为快速收紧或松开而设计。",
    "feature": "属于“摩擦结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k137.jpg"
  },
  {
    "id": "k138",
    "name": "中间八字结",
    "english": "In-Line Figure Eight Loop；Directional Figure 8 Loop；Single Figure Eight on the Bight",
    "alias": "",
    "category": "八字结系列",
    "categoryId": "cat_06",
    "usage": "中间八字结是一种套结。可以在绳子中间打结，无需使用绳子端部。该套结仅可在一个方向受载，否则绳结会被破坏。它可以用在吊拉绳中，形成可用作手环的套结。",
    "feature": "属于“八字结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k138.jpg"
  },
  {
    "id": "k139",
    "name": "兔耳结",
    "english": "Double Bight Figure Eight；Bunny Ears；Y-Hang；Double Figure 8 Loop；Double Flemish Loop；Double Loop Figure Eight；Canadian Eight；Canadian Figure 8",
    "alias": "双股的八字结",
    "category": "八字结系列",
    "categoryId": "cat_06",
    "usage": "兔耳结常用于在攀岩时平衡二个地锚，还可以提供冗余度。与其他许多双环绳结相比，兔耳结牢固安全，将绳子从一环移向另一环就可以轻松容易地调整绳环大小。每个绳环分摊约50%的载荷。若任意绳环、任意地锚或任意登山扣受损，则不能勉强使用其余的地锚组合。",
    "feature": "属于“八字结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k139.jpg"
  },
  {
    "id": "k140",
    "name": "八字套结",
    "english": "Figure Eight Loop；Flemish Loop；Figure Eight on",
    "alias": "八字结绳耳；双八字结；八字结绳圈",
    "category": "八字结系列",
    "categoryId": "cat_06",
    "usage": "八字套结用于在绳子端部形成一个固定的绳环。它打结相对容易，并且牢固，但是重载后会非常难以解开。",
    "feature": "属于“八字结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k140.jpg"
  },
  {
    "id": "k141",
    "name": "八字结",
    "english": "Figure Eight；Flemish Knot；Savoy Knot；Figure of Eight Knot",
    "alias": "单八字结",
    "category": "八字结系列",
    "categoryId": "cat_06",
    "usage": "在许多情况下，八字结是替代普通反手结的一个通用止索结。在航海和攀岩中，八字结十分重要，因为需要止索结来阻止装置脱出。",
    "feature": "属于“八字结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k141.jpg"
  },
  {
    "id": "k142",
    "name": "八字返穿结",
    "english": "Figure Eight Follow Through；Figure Eight Retrace；Rerouted Figure Eight Loop；Threaded Figure Eight Loop",
    "alias": "穿式八字结；翻穿双八字结",
    "category": "八字结系列",
    "categoryId": "cat_06",
    "usage": "八字返穿结常用于攀岩和洞穴探险（绳子张力中等），用于在绳子端部或环绕物体形成一个固定的绳环。它解开相对容易并且牢固，但是重载后会变得难以解开。当绳结必须系在无法轻易套上绳环的物体时，可使用“重新编结”的方法。特别的，它可用于将绳子系在攀岩安全带上。双环称人结可以完成同样的任务，打结更快并且不会死结，但是对于初学者来说，八字返穿结更容易上手，可快速检查打结是否正确。",
    "feature": "属于“八字结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k142.jpg"
  },
  {
    "id": "k143",
    "name": "八字连接结",
    "english": "Figure Eight Bend；Flemish Bend；Rewoven Figure Eight",
    "alias": "八字接结；加固用的八字内结",
    "category": "八字结系列",
    "categoryId": "cat_06",
    "usage": "八字连接结通常被视为一种牢固的绳结，它采用简单的方法连接两段近似直径的绳子，通常容易解开。八字连接结是“重新编结”的八字结，意思是一根绳子的端部系八字结，然后第二根绳子并排沿着第一根绳子的转折，但是沿相反方向。",
    "feature": "属于“八字结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k143.jpg"
  },
  {
    "id": "k144",
    "name": "双八字结",
    "english": "Offset Figure Eight Bend；Abnormal Figure Eight Bend；Double Figure Eight；Flat Figure Eight Bend",
    "alias": "",
    "category": "八字结系列",
    "categoryId": "cat_06",
    "usage": "双八字结就是用两根对折的绳子系成的一个八字结。该结比正常的八字连接结要差一些。当使用时，两根绳子的直径必须相同。双八字结并不牢固，应该避免使用。",
    "feature": "属于“八字结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k144.jpg"
  },
  {
    "id": "k145",
    "name": "滑八字结",
    "english": "Slip Figure Eight；Slipped Figure Eight Knot",
    "alias": "活八字结",
    "category": "八字结系列",
    "categoryId": "cat_06",
    "usage": "这种绳结用来在绳索中间形成一个可调节的套索。",
    "feature": "属于“八字结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k145.jpg"
  },
  {
    "id": "k146",
    "name": "三叶结",
    "english": "Trefoil Knot；Triquetra；Valknut",
    "alias": "",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "三叶结无法物理绑结，因为它没有端点。以笔者的观点，此经典绳结的简单性、对称性和其中的美使它值得列入应用程序。它与艺术、宗教和数学息息相关。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k146.jpg"
  },
  {
    "id": "k147",
    "name": "通用绳头结",
    "english": "Common Whipping；Plain Whipping；Ordinary Whipping；Wolf Whipping",
    "alias": "",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "普通绳头结是最基本的一种绳头结，目的就是要防止绳索缠在一起。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k147.jpg"
  },
  {
    "id": "k148",
    "name": "缩短结",
    "english": "Sheepshank；Trumpet Knot；Catshank；Dogshank；Kamikaze Knot",
    "alias": "羊脚结；缩绳结；神风结",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "缩短结通常用于缩短绳索或收紧绳索。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k148.jpg"
  },
  {
    "id": "k149",
    "name": "水手收绳结",
    "english": "Sailor's Coil",
    "alias": "水手收绳圈",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "水手收绳结通常在海上存放绳索中使用。捆扎绳圈的绳结可以承受相当大的拉力而不会散开。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k149.jpg"
  },
  {
    "id": "k150",
    "name": "GRIEF 结",
    "english": "Grief Knot；Whatnot；Grass Bend；Reeving Line Bend",
    "alias": "悲伤结",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "Grief结是一种结合了祖母结与贼结特点的绳结，结成的绳结不经常在工作中使用，但是在魔术中确实有一些实际的用处。它的名字，是英文\"granny\"和\"thief\"的组合。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k150.jpg"
  },
  {
    "id": "k151",
    "name": "瑞士腰胯结",
    "english": "Swiss Seat；Rappel Seat",
    "alias": "简易绳降安全结；绳降腰胯结；瑞士座椅；座位席结",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "瑞士腰胯结（绳降腰胯结）是一种基本但却有效的绳降安全结，可使用绳索或织带轻松制作。它非常适合在紧急情况下需要临时制作安全结或不想购买商业安全结的人员。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k151.jpg"
  },
  {
    "id": "k152",
    "name": "束帆收绳结",
    "english": "Gasket Coil；Buntline Coil",
    "alias": "捆绑绳圈",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "捆绑绳圈是一种存放绳索以防止其缠绕的干净整洁方式。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k152.jpg"
  },
  {
    "id": "k153",
    "name": "敲钟的人结",
    "english": "Bell Ringer's Knot；Half Sheepshank",
    "alias": "",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "暂无用途说明，可后续补充。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k153.jpg"
  },
  {
    "id": "k154",
    "name": "西部绳端结",
    "english": "West Country Whipping",
    "alias": "",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "西部绳端结的目的是固定和防止绳索散开。这种方法不需要任何工具。它对大直径绳索和线缆特别有效。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k154.jpg"
  },
  {
    "id": "k155",
    "name": "皇冠结",
    "english": "Crown Knot",
    "alias": "冠结",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "皇冠结是避免三股绳索磨损的绳端反穿结的起始结。它也是一些装饰性绳结的组成部分。从侧面看去，该结与国王的皇冠有些类似，因而得名。这个名字还说明绳结的位置在绳头或绳尾。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k155.jpg"
  },
  {
    "id": "k156",
    "name": "消防员收绳结",
    "english": "Fireman's Coil；Fireman Coil",
    "alias": "双滑绳圈",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "双滑绳圈是一种用于缠绕和存放绳索的有效方法。它具有一个可将绳索挂于钩子或防滑钉上的环。通过对简单拖拉绳索端部可快速释放系住绳圈的绳结。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k156.jpg"
  },
  {
    "id": "k157",
    "name": "辫子结",
    "english": "Single Rope Braid；Twist Braid；Trumpet Cord",
    "alias": "",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "辫子结可用于编织手链或其他装饰物。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k157.jpg"
  },
  {
    "id": "k158",
    "name": "友谊结",
    "english": "Friendship Knot；Square Knot；Neckerchief Knot；Scarf Knot；Success Knot；Japanese Crown Knot；Rustler's Knot；Buckaroo Knot",
    "alias": "",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "友谊结用于以时尚的装饰方法将围巾松散的末端系牢。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k158.jpg"
  },
  {
    "id": "k159",
    "name": "双线结",
    "english": "Double Coin Knot；Josephine Knot；Wake Knot",
    "alias": "",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "双线结又名中国结，是装饰性的大绳接结。它常用作其他更为复杂的装饰性绳结的基础。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k159.jpg"
  },
  {
    "id": "k160",
    "name": "反穿结",
    "english": "Back Splice；End Splice",
    "alias": "倒织结；绳端织结",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "反穿结常用于打结三股绳索的绳端，防止绳索磨损。系结方法为先打开绳股，绑皇冠结，再沿绳子向里交叉编织绳股。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k160.jpg"
  },
  {
    "id": "k161",
    "name": "波尔多滑轮结",
    "english": "Poldo Tackle",
    "alias": "波尔多索结；波尔多系统",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "波尔多滑轮结是一种高度通用、可调节的紧张系统，专为快速收紧或松开而设计。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k161.jpg"
  },
  {
    "id": "k162",
    "name": "巫毒结",
    "english": "Voodoo Hitch；Transport Hitch；PM Hitch（Pure Magic）",
    "alias": "巫毒系统；运输结；巫毒滑轮结",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "巫毒结，亦称运输结，是一种卓越的紧张系统。它提供一种简易的方法，向固定绳索增加易于调节的张力。巫毒结广泛应用于各个领域，包括激流救援。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k162.jpg"
  },
  {
    "id": "k163",
    "name": "凯尔特结",
    "english": "Celtic Knot；Celtic Mat；Celtic Plait；Icovellavna",
    "alias": "",
    "category": "特殊绳结",
    "categoryId": "cat_07",
    "usage": "凯尔特结是多种复杂织物形状的通用描述。上面的表述是一个矩形形状，可以在装饰性织物垫上增加额外的线圈。",
    "feature": "属于“特殊绳结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k163.jpg"
  },
  {
    "id": "k164",
    "name": "三重反手结",
    "english": "Triple Overhand Knot；Franciscan Friar's Knot；Threefold Overhand Knot；Barrel Knot；Friar's Knot；French Monk's Knot；Monk's Knot；Hoodie String Knot",
    "alias": "",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "暂无用途说明，可后续补充。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k164.jpg"
  },
  {
    "id": "k165",
    "name": "同心结",
    "english": "True Lover's Knot；True Love Knot；Two Cord Lanyard Knot",
    "alias": "",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "同心结这个名字用于许多不同的结上。上面描述的同心结就是许多这种命名结中的一个。相互缠绕的反手结代表两人间相互结合的爱情的象征。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k165.jpg"
  },
  {
    "id": "k166",
    "name": "渔人结",
    "english": "Fisherman's Knot；Waterman's Knot；Angler's Knot；Englishman's Knot",
    "alias": "拖曳结；英人结；英式结；单渔人结",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "渔人结用于连接两段等直径的绳线。尽管该结适用于钓鱼，但是仍有其他绳结可以提供更加优越的性能，如手足结。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k166.jpg"
  },
  {
    "id": "k167",
    "name": "多个反手结",
    "english": "Multiple Overhand Knot；Heaving Line Knot；Multi-fold Overhand Knot；French Knot；Quipu；Khipu",
    "alias": "桶结；血结",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "暂无用途说明，可后续补充。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k167.jpg"
  },
  {
    "id": "k168",
    "name": "水结",
    "english": "Water Knot；Tape Knot；Grass Knot；Ring Bend；Rewoven Overhand Knot",
    "alias": "环固结",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "水结常用于在攀登中连接两条织带的末端。水结是一种“重新编结”的反手结，意思是一个反手结绑在一条绳索/织带的端部，然后第二条绳索平行于第一条，但沿反方向旋转。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k168.jpg"
  },
  {
    "id": "k169",
    "name": "半扣结",
    "english": "Half Hitch；Single Hitch",
    "alias": "半结",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "半扣结是简单的反手结的变种。绳结本身并不牢固，但它是各种有用且可靠的套结、绳套和绳结的重要组成部分。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k169.jpg"
  },
  {
    "id": "k170",
    "name": "齐柏林结",
    "english": "Zeppelin Bend；Rosendahl Bend",
    "alias": "飞艇结",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "齐柏林结是一种通用的连接结。它以牢固，容易打结，防死结的方式来连接两根绳索，据说这可能是连接两根绳子的最佳好方式。虽然打结的简单性和牢固性可能与其他绳结相当，但是解开绳结，甚至重载后解开绳结的能力却独一无二。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k170.jpg"
  },
  {
    "id": "k171",
    "name": "SCAFFOLD 结",
    "english": "Scaffold Knot；Triple Overhand Noose",
    "alias": "三重反手套索结",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "SCAFFOLD结用于将绳索连接到登山扣、卸扣或导轨上。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k171.jpg"
  },
  {
    "id": "k172",
    "name": "捕兽结",
    "english": "Fisherman's Eye；Middleman's Knot；Fisherman's Loop；Englishman's Loop；True Lover's Knot",
    "alias": "络头结；中间人结",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "补兽结是一种由至少四种不同方法其一结在绳圈上的有用绳结，其中一种绳结被称作同心结。该绳结曾经常被攀岩绳上的中间人使用，但如今已被更好的绳结（如蝴蝶结）替代。钓鱼者也使用它结成一个主环，但是也有更适用于此的绳结，如络头结。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k172.jpg"
  },
  {
    "id": "k173",
    "name": "艾希礼结",
    "english": "Ashley's Bend",
    "alias": "阿什利结",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "艾希礼结和齐柏林结相似，由两个互锁的反手结构成，用于连接两条绳子。它非常难以解开。该结由Clifford Ashley发明，用于连接较刚硬的易滑脱材料。在Ashley的测试中，该结与手足结相同，完全不会滑脱。经测试，其他所有绳结均有一定的滑脱。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k173.jpg"
  },
  {
    "id": "k174",
    "name": "亨特结",
    "english": "Hunter's Bend；Rigger's Bend",
    "alias": "猎人结；索架结；杭特接结",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "亨特结用于连接两条直径相近的绳索。因为不易解开，是一个连接细股绳或滑绳的很好的打结法。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k174.jpg"
  },
  {
    "id": "k175",
    "name": "双圈索结",
    "english": "Poacher's Knot；Tenkara One Knot；Double Overhand Sliding Loop；Double Overhand Noose；Strangle Snare；Two-Turn Scaffold Knot；Surveyor's Knot；Barrel Knot；DONK(Double Overhand Noose Knot)；Evans Knot...",
    "alias": "主线双联结；偷猎者结；双反手滑套结；DON结",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "双圈索结是一种非常牢固的绳结，被登山者用于捆绑绳索和登山用铁索。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k175.jpg"
  },
  {
    "id": "k176",
    "name": "双渔人结",
    "english": "Double Fisherman's Knot；Grapevine Knot；Double Englishman's Knot；Double English Knot；Necklace Knot；Tilley Hat Knot",
    "alias": "即葡萄藤结",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "双渔人结用于连接两段绳子。该结最常用于攀岩，栽培，搜寻和救援。该结的主要用途是形成高强度的绳环，叫普鲁士环，用于连接攀岩保护系统的各个部件。双渔人结还能用于连接项链绳的端部。向里或者向外滑动绳结可以调整项链长度。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k176.jpg"
  },
  {
    "id": "k177",
    "name": "双反手结",
    "english": "Double Overhand Knot；Blook Knot",
    "alias": "双单结",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "双反手结主要是其他绳结的基础结，包括外科结的第一结和双渔人结的两侧。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k177.jpg"
  },
  {
    "id": "k178",
    "name": "反手连接结",
    "english": "Flat Overhand Bend；EDK；Euro Death Knot；Offset Water Knot；One-Sided Overhand Bend；Thumb Bend；Thumb Knot；Openhand Knot；Creeler's Knot；European Death Knot",
    "alias": "普通绳头结",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "反手连接结是用来把两根绳索并在一起的绳结。在攀岩和登山时会用到它。同时，在日常生活中人们也会经常用到它，因为这种绳结是最容易绑的绳结之一。尽管在美国它有个外号叫“欧洲死亡结”，但是反手连接结在绕绳下降时使用，会有它的优势。因为这种绳结可以抵消张力轴，它比其它类型的绳结更容易在粗糙的表面滑动。除了它个头很小之外，在取回绳索时，它还有助于减少绳子卡在边缘、裂缝或下降设备上的可能性。绳子如果卡在下降途中，就会对攀爬者带来很大的危险，所以这种绳结有了这些优势，加上它又很容易绑，自然就很受欢迎。有些警告会建议大家把绳索的尾部留长一些（超过半米），而且绳结要小心扎好，把4股绳子都分别一一拉紧，然后让这种绳结只承受一般的下降重力。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k178.jpg"
  },
  {
    "id": "k179",
    "name": "三叶结",
    "english": "Trefoil Knot；Triquetra；Valknut",
    "alias": "",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "三叶结无法物理绑结，因为它没有端点。以笔者的观点，此经典绳结的简单性、对称性和其中的美使它值得列入应用程序。它与艺术、宗教和数学息息相关。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k179.jpg"
  },
  {
    "id": "k180",
    "name": "双反手环",
    "english": "Surgeon's Loop；Double Loop；Double Overhand Loop",
    "alias": "外科环",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "双反手环是一种结实、容易打结的固定绳环，通常与鱼线一起使用。此绳结有点笨重，但在绳线和引导绳端部快速结成牢固的绳环并连接绳环时非常棒。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k180.jpg"
  },
  {
    "id": "k181",
    "name": "双重单结",
    "english": "Loop Knot；Overhand Loop",
    "alias": "反手结绳耳",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "双重单结是一个简单的绳结，它在一条绳子上形成一个固定的绳环。在绳圈上绑一个反手结，它可以沿绳索绑在绳子的任何地方。该结可用于连接夹子，钩子和其他绳索等，但是它的缺点是，当绳索承受负荷时它可能会变成死结，可能需要剪断绳结。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k181.jpg"
  },
  {
    "id": "k182",
    "name": "反手结",
    "english": "Backhand Hitch；High Tie；High Safety Knot",
    "alias": "",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "反手结通常在固定运送荷载时被用作锚。当绳索受力时，反手结很容易解开。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k182.jpg"
  },
  {
    "id": "k183",
    "name": "滑结",
    "english": "Slipped Overhand Knot；Slip Knot；Running Knot；Noose",
    "alias": "活结；简单的活索",
    "category": "反手结系列",
    "categoryId": "cat_08",
    "usage": "活结和滑结是大多数绳结的常用术语，表明拉动绳索自由端能够很容易解开绳结。打滑的反手结是这种结中最简单的，常叫做滑结或活结，虽然这是含义宽泛的术语。在历史上，这种简单的绳结用于诱捕鸟类和其他小动物。它也可以被用作可以快速解开的止索结。",
    "feature": "属于“反手结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k183.jpg"
  },
  {
    "id": "k184",
    "name": "包裹结",
    "english": "Packer's Knot；Butcher's Knot；Parcel Knot；Meat Packer's Knot",
    "alias": "",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "包裹结是一种捆绑绳结，易于收紧并快速在原位锁定。它多数由 细索或细绳制成，用于打包及捆肉。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k184.jpg"
  },
  {
    "id": "k185",
    "name": "外科结",
    "english": "Surgeon's Knot；Ligature Knot",
    "alias": "",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "外科结是平结的一个简单修改。当打结第一部分时，它增加了一个额外的扭曲，因而增加了摩擦，使绳结更牢固。当保持缝合线张力十分重要时，外科医生一般使用此绳结。外科结也可用在钓鱼时绑苍蝇以及缝被子。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k185.jpg"
  },
  {
    "id": "k186",
    "name": "天线袋口滑结",
    "english": "Slipped Ground-line Hitch；Slipped Spar Hitch；Fender Knot；Miller's Knot；Sack Knot；Bag Knot",
    "alias": "基线套钩滑结",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "这种绳结可以用来将绳索临时系于立柱上。它也可以用来捆绑包袋的开口，解开也很快速简便。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k186.jpg"
  },
  {
    "id": "k187",
    "name": "天线袋口结",
    "english": "Ground-line Hitch；Spar Hitch；Picker-line Hitch；Fender Knot；Miller's Knot；Sack Knot；Bag Knot",
    "alias": "",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "这种绳结可以用来把绳索系在立柱上，或者把细绳系在粗绳上。在划船和帆船应用中，该绳结用于将物体系在栏杆之上。它也可以用来栓马。这种绳结还可以用来扎紧包袋的开口，通常可以快速松懈，使内容物易于拿取。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k187.jpg"
  },
  {
    "id": "k188",
    "name": "收缩结",
    "english": "Constrictor Knot；Gunner's Knot；Whip Knot；Timber Knot；Timmerknut",
    "alias": "缩紧结",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "收缩结是最有效的捆绑结之一。它简单、牢固，一旦系紧后很难或者不可能解开。收缩结适合于需要临时固定或者半永久绑定的情况。收缩结当作软管夹或者电缆夹也很好用。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k188.jpg"
  },
  {
    "id": "k189",
    "name": "贼结",
    "english": "Thief Knot；Bag Knot；Bread Bag Knot",
    "alias": "压缆结",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "贼结酷似平结，但自由绳端在十字相对侧。据说水手们常用贼结将他们的财物固定在包中，绳端不外露。若其他水手搜查这个包时，小偷一般会使用更加常见的平结再绑好包，这说明包已经被偷过了，因而得此名。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k189.jpg"
  },
  {
    "id": "k190",
    "name": "祖母结",
    "english": "Granny Knot；False Knot；Lubber's Knot；Calf Knot；Booby Knot；Garden Knot；Bourchier Knot",
    "alias": "外行平结",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "祖母结是一种捆绑结，可以用来将绳子或线绳固定在物体（如背包或包裹）周围。但是，针对此，其他绳结（如平结）更加优秀，因此实际应用中很少使用祖母结。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k190.jpg"
  },
  {
    "id": "k191",
    "name": "平结",
    "english": "Square Knot；Reef Knot；Hercules Knot",
    "alias": "索帆结",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "平结是一种古老而简单的捆绑结，用于绕一个物体固定绳索或绳线。另外，它还被水手用于收帆；它还是装饰性花边纺织品的重要绳结之一。当用布打结时，此结会变得很平整，历史上曾用于绑绷带。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k191.jpg"
  },
  {
    "id": "k192",
    "name": "领圈结",
    "english": "Turk's Head(Mat)；Turk's Head 3 Lead 5 Bight；THK；Sailor's Knot",
    "alias": "环扣结；三股花箍；领巾圈结",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "该类结称为领圈结，本质上是连续的辫子结。领圈结可以是平整的，形成一个装饰性的垫子；或者成环状，绕在杆子或棍棒周围。有时，第二种形式还被童子军用作领巾的滑结。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k192.jpg"
  },
  {
    "id": "k193",
    "name": "领圈结",
    "english": "Turk's Head（Woggle）；Woggle；Neckerchief Slide；THK；Braided Ring；Turk's Head 3 Lead 5 Bight；Sailor's knot",
    "alias": "环扣结；三股花箍；领巾圈结",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "该类结称为领圈结，本质上是连续的辫子结。领圈结可以是平整的，形成一个装饰性的垫子；或者成环状，绕在杆子或棍棒周围。有时，第二种形式还被童子军用作领巾的滑结。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k193.jpg"
  },
  {
    "id": "k194",
    "name": "林地扎带结",
    "english": "Woodland Zip-tie；Bedroll Knot；Cow Hitch Lock Knot",
    "alias": "铺盖卷结",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "暂无用途说明，可后续补充。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k194.jpg"
  },
  {
    "id": "k195",
    "name": "拉普结",
    "english": "Lapp Knot；False Sheet Bend；Lap Knot；Lapp Bend；Girdle Knot",
    "alias": "",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "这种绳结用来将两根绳索打结在一起。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k195.jpg"
  },
  {
    "id": "k196",
    "name": "双重收缩结",
    "english": "Double Constrictor",
    "alias": "",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "双重收缩结是一种较为安全的收缩结。双重收缩结适用于需要临时性安全捆绑的情况。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k196.jpg"
  },
  {
    "id": "k197",
    "name": "滑拉普结",
    "english": "Slipped Lapp Knot；Slipped Lapp Bend；Adjustable Drawstring Knot；Gym Shorts Knot；Quick Hitch",
    "alias": "",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "这种绳结很受欢迎，可用于运动短裤和类似装备（运动裤、泳裤、手术衣等）或浴袍上的可调节拉绳。它也可以用作捆状或卷状物品的捆扎结。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k197.jpg"
  },
  {
    "id": "k198",
    "name": "瓶口结",
    "english": "Jar Sling Knot（bight method）；Bottle Sling Knot；Jug Sling；Spanish Hackamore；Bridle Knot；Moonshiner's Knot",
    "alias": "瓶吊结",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "瓶口结可以用于为易滑脱的窄颈玻璃容器或陶瓷容器编制一个提手，只要瓶颈在瓶口处会轻微扩张。该结还可用于充当临时的驯马笼头或者应急马勒，绳结中的二个中央反手结作为马嚼子，其中一个外绳圈穿过动物口套的上方，另一个穿过下颌下部。该结本身较为美观，可以用作装饰性绳结，如作为挂带。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k198.jpg"
  },
  {
    "id": "k199",
    "name": "瓶口结",
    "english": "Jar Sling Knot（end method）；Bottle Sling Knot；Jug Sling；Spanish Hackamore；Bridle Knot；Moonshiner's Knot",
    "alias": "瓶吊结",
    "category": "绑扎类",
    "categoryId": "cat_09",
    "usage": "瓶口结可以用于为易滑脱的窄颈玻璃容器或陶瓷容器编制一个提手，只要瓶颈在瓶口处会轻微扩张。该结还可用于充当临时的驯马笼头或者应急马勒，绳结中的二个中央反手结作为马嚼子，其中一个外绳圈穿过动物口套的上方，另一个穿过下颌下部。该结本身较为美观，可以用作装饰性绳结，如作为挂带。",
    "feature": "属于“绑扎类”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k199.jpg"
  },
  {
    "id": "k200",
    "name": "外科结（钓鱼）",
    "english": "Surgeon's Knot（Fishing）；Double Overhand Bend；Double Surgeon's knot",
    "alias": "",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "外科结通常用在飞蝇钓中用于连接两股绳索。它可简单快速地打好，适用于直径相等或不等的线绳。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k200.jpg"
  },
  {
    "id": "k201",
    "name": "大绳接结",
    "english": "Carrick Bend；Pretzel Knot",
    "alias": "单花联结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "大绳接结是用于连接两条绳子的结子。它尤其适用于太粗太僵硬而无法结成其他普通绳结的重型绳子或绳缆。甚至在承受很大载荷或者浸水后，绳结也不会结死。大绳接结美观、相互编织的形状使其具有装饰性。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k201.jpg"
  },
  {
    "id": "k202",
    "name": "水结",
    "english": "Water Knot；Tape Knot；Grass Knot；Ring Bend；Rewoven Overhand Knot",
    "alias": "环固结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "水结常用于在攀登中连接两条织带的末端。水结是一种“重新编结”的反手结，意思是一个反手结绑在一条绳索/织带的端部，然后第二条绳索平行于第一条，但沿反方向旋转。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k202.jpg"
  },
  {
    "id": "k203",
    "name": "阿尔贝托结",
    "english": "Alberto Knot；Crazy Alberto Knot；Modified Albright Knot",
    "alias": "",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "阿尔贝托结用于连接不同直径的鱼线。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k203.jpg"
  },
  {
    "id": "k204",
    "name": "阿尔卑斯中间衔接结",
    "english": "Alpine Butterfly Bend；Butterfly Bend；Strait Bend",
    "alias": "",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "高山蝴蝶连接结用于连接两条尺寸相同的绳索的末端。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k204.jpg"
  },
  {
    "id": "k205",
    "name": "FG 结",
    "english": "FG Knot",
    "alias": "",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "FG结用于盐水钓鱼。这是个非常结实的结，用于连接两条不同直径的线。FG结很平滑，且很容易穿过导线。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k205.jpg"
  },
  {
    "id": "k206",
    "name": "捆扎结",
    "english": "Racking Bend",
    "alias": "",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "捆扎结是一种使用“八字”编扎方法连接两股不同直径绳索的结。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k206.jpg"
  },
  {
    "id": "k207",
    "name": "手足结",
    "english": "Blood Knot；Barrel Knot",
    "alias": "血结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "手足结是用于连接两条鱼线，并保留大部分鱼线强度的最常用绳结。使用其他绳结连接鱼线会严重降低鱼线的强度。绳结很容易缠绕，对于鱼线来说这并不是个问题，但是对普通绳索来说则可能会有影响。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k207.jpg"
  },
  {
    "id": "k208",
    "name": "齐柏林结",
    "english": "Zeppelin Bend；Rosendahl Bend",
    "alias": "飞艇结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "齐柏林结是一种通用的连接结。它以牢固，容易打结，防死结的方式来连接两根绳索，据说这可能是连接两根绳子的最佳好方式。虽然打结的简单性和牢固性可能与其他绳结相当，但是解开绳结，甚至重载后解开绳结的能力却独一无二。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k208.jpg"
  },
  {
    "id": "k209",
    "name": "REEVER 结",
    "english": "Reever Knot；Reever Bend",
    "alias": "REEVER 连接结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "REEVER结是一种连接两条绳索的安全方式。它也是少数适合将弹力绳系在一起的结扣之一。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k209.jpg"
  },
  {
    "id": "k210",
    "name": "YUCATAN 结",
    "english": "Yucatan Knot；Worm Knot；Reverse Albright Knot；Reverse Knot",
    "alias": "尤卡坦半岛结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "在钓鱼中，YUCATAN结有一个从细到粗的线接头，用于绑结较粗的绳子。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k210.jpg"
  },
  {
    "id": "k211",
    "name": "奥尔布赖特结",
    "english": "Albright Special；Albright Knot",
    "alias": "工程蝴蝶结；中间结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "奥尔布赖特结是一种牢固的绳结，用于连接2根直径不同的鱼线。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k211.jpg"
  },
  {
    "id": "k212",
    "name": "八字连接结",
    "english": "Figure Eight Bend；Flemish Bend；Rewoven Figure Eight",
    "alias": "八字接结；加固用的八字内结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "八字连接结通常被视为一种牢固的绳结，它采用简单的方法连接两段近似直径的绳子，通常容易解开。八字连接结是“重新编结”的八字结，意思是一根绳子的端部系八字结，然后第二根绳子并排沿着第一根绳子的转折，但是沿相反方向。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k212.jpg"
  },
  {
    "id": "k213",
    "name": "钉子结",
    "english": "Nail Knot；Tube Knot；Gryp Knot",
    "alias": "",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "钉子结，也叫管结，主要是在木工活和用假绳钓鱼时使用。钉子结之所以叫这个名字，是因为穿过这根线时会插入一个钉子作为引导。一般来讲，用一根小吸管会更容易一些。该钉子结被用来把不同直径的线并在一起，让线的直径可以尽量减小。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k213.jpg"
  },
  {
    "id": "k214",
    "name": "接绳结",
    "english": "Sheet Bend；Weaver's Knot；Becket Bend",
    "alias": "单编结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "接绳结最好用于连接两个尺寸不等的绳索。较粗的绳索应该用作简单的绳圈。若绳索尺寸相同，它同样适用。对于许多人来说，这是个“必须”的绳结。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k214.jpg"
  },
  {
    "id": "k215",
    "name": "钻石结",
    "english": "Diamond Knot；Lanyard Knot；Knife Lanyard Knot；Two-strand Diamond Knot；Bosun's Whistle Knot",
    "alias": "刀挂绳结；挂绳结；刀具手柄挂绳",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "钻石结是一种常用于挂绳的装饰性绳结。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k215.jpg"
  },
  {
    "id": "k216",
    "name": "双马具连接结",
    "english": "Double Harness Bend；Double Harness Bend with Parallel Ends",
    "alias": "",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "双马具连接结易于打结，使用的材料极少，但却是连接两块尺寸相同的皮革、两条尺寸相同的细绳或细线的牢固而安全的方式。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k216.jpg"
  },
  {
    "id": "k217",
    "name": "双邓肯环",
    "english": "Uni-to-Uni Knot；Double Grinner Knot；Double Uni Knot",
    "alias": "双万能结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "双邓肯环用于在钓鱼时连接两条鱼线。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k217.jpg"
  },
  {
    "id": "k218",
    "name": "双龙连接结",
    "english": "Double Dragon Bend",
    "alias": "双龙结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "双龙连接结推荐用于连接两条尺寸相同的绳索。这种结扣可能很难解开。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k218.jpg"
  },
  {
    "id": "k219",
    "name": "双接绳结",
    "english": "Double Sheet Bend；Double Becket Bend",
    "alias": "",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "与接绳结一样，双接绳结常被用于连接两段不同尺寸的绳子，但增加了额外的安全措施，尤其是当两段绳子的尺寸差异很明显时。较粗的绳子应用作简单环。若绳子的尺寸相同，该结一样好用。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k219.jpg"
  },
  {
    "id": "k220",
    "name": "同心结",
    "english": "True Lover's Knot；True Love Knot；Two Cord Lanyard Knot",
    "alias": "",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "同心结这个名字用于许多不同的结上。上面描述的同心结就是许多这种命名结中的一个。相互缠绕的反手结代表两人间相互结合的爱情的象征。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k220.jpg"
  },
  {
    "id": "k221",
    "name": "渔人结",
    "english": "Fisherman's Knot；Waterman's Knot；Angler's Knot；Englishman's Knot",
    "alias": "拖曳结；英人结；英式结；单渔人结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "渔人结用于连接两段等直径的绳线。尽管该结适用于钓鱼，但是仍有其他绳结可以提供更加优越的性能，如手足结。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k221.jpg"
  },
  {
    "id": "k222",
    "name": "艾希礼结",
    "english": "Ashley's Bend",
    "alias": "阿什利结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "艾希礼结和齐柏林结相似，由两个互锁的反手结构成，用于连接两条绳子。它非常难以解开。该结由Clifford Ashley发明，用于连接较刚硬的易滑脱材料。在Ashley的测试中，该结与手足结相同，完全不会滑脱。经测试，其他所有绳结均有一定的滑脱。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k222.jpg"
  },
  {
    "id": "k223",
    "name": "亨特结",
    "english": "Hunter's Bend；Rigger's Bend",
    "alias": "猎人结；索架结；杭特接结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "亨特结用于连接两条直径相近的绳索。因为不易解开，是一个连接细股绳或滑绳的很好的打结法。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k223.jpg"
  },
  {
    "id": "k224",
    "name": "拉普结",
    "english": "Lapp Knot；False Sheet Bend；Lap Knot；Lapp Bend；Girdle Knot",
    "alias": "",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "这种绳结用来将两根绳索打结在一起。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k224.jpg"
  },
  {
    "id": "k225",
    "name": "双渔人结",
    "english": "Double Fisherman's Knot；Grapevine Knot；Double Englishman's Knot；Double English Knot；Necklace Knot；Tilley Hat Knot",
    "alias": "即葡萄藤结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "双渔人结用于连接两段绳子。该结最常用于攀岩，栽培，搜寻和救援。该结的主要用途是形成高强度的绳环，叫普鲁士环，用于连接攀岩保护系统的各个部件。双渔人结还能用于连接项链绳的端部。向里或者向外滑动绳结可以调整项链长度。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k225.jpg"
  },
  {
    "id": "k226",
    "name": "双八字结",
    "english": "Offset Figure Eight Bend；Abnormal Figure Eight Bend；Double Figure Eight；Flat Figure Eight Bend",
    "alias": "",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "双八字结就是用两根对折的绳子系成的一个八字结。该结比正常的八字连接结要差一些。当使用时，两根绳子的直径必须相同。双八字结并不牢固，应该避免使用。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k226.jpg"
  },
  {
    "id": "k227",
    "name": "反手连接结",
    "english": "Flat Overhand Bend；EDK；Euro Death Knot；Offset Water Knot；One-Sided Overhand Bend；Thumb Bend；Thumb Knot；Openhand Knot；Creeler's Knot；European Death Knot",
    "alias": "普通绳头结",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "反手连接结是用来把两根绳索并在一起的绳结。在攀岩和登山时会用到它。同时，在日常生活中人们也会经常用到它，因为这种绳结是最容易绑的绳结之一。尽管在美国它有个外号叫“欧洲死亡结”，但是反手连接结在绕绳下降时使用，会有它的优势。因为这种绳结可以抵消张力轴，它比其它类型的绳结更容易在粗糙的表面滑动。除了它个头很小之外，在取回绳索时，它还有助于减少绳子卡在边缘、裂缝或下降设备上的可能性。绳子如果卡在下降途中，就会对攀爬者带来很大的危险，所以这种绳结有了这些优势，加上它又很容易绑，自然就很受欢迎。有些警告会建议大家把绳索的尾部留长一些（超过半米），而且绳结要小心扎好，把4股绳子都分别一一拉紧，然后让这种绳结只承受一般的下降重力。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k227.jpg"
  },
  {
    "id": "k228",
    "name": "滑拉普结",
    "english": "Slipped Lapp Knot；Slipped Lapp Bend；Adjustable Drawstring Knot；Gym Shorts Knot；Quick Hitch",
    "alias": "",
    "category": "连接结",
    "categoryId": "cat_10",
    "usage": "这种绳结很受欢迎，可用于运动短裤和类似装备（运动裤、泳裤、手术衣等）或浴袍上的可调节拉绳。它也可以用作捆状或卷状物品的捆扎结。",
    "feature": "属于“连接结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k228.jpg"
  },
  {
    "id": "k229",
    "name": "帆索滑结",
    "english": "Slipped Buntline Hitch；Quick Release Buntline",
    "alias": "快解帆索结",
    "category": "快松结",
    "categoryId": "cat_11",
    "usage": "帆索滑结用于将绳索连接到需要安全结扣但仍可快速轻松地解开的圆环、柱子或栏杆上。",
    "feature": "属于“快松结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k229.jpg"
  },
  {
    "id": "k230",
    "name": "吊床结",
    "english": "Becket Hitch（Slipped）；Hammock Knot；Quick Release Becket Hitch",
    "alias": "",
    "category": "快松结",
    "categoryId": "cat_11",
    "usage": "吊床结在吊床露营社区很流行，因为它结绳的速度快而且绑和解绑简单。",
    "feature": "属于“快松结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k230.jpg"
  },
  {
    "id": "k231",
    "name": "天线袋口滑结",
    "english": "Slipped Ground-line Hitch；Slipped Spar Hitch；Fender Knot；Miller's Knot；Sack Knot；Bag Knot",
    "alias": "基线套钩滑结",
    "category": "快松结",
    "categoryId": "cat_11",
    "usage": "这种绳结可以用来将绳索临时系于立柱上。它也可以用来捆绑包袋的开口，解开也很快速简便。",
    "feature": "属于“快松结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k231.jpg"
  },
  {
    "id": "k232",
    "name": "活索结",
    "english": "Mooring Hitch",
    "alias": "码头索",
    "category": "快松结",
    "categoryId": "cat_11",
    "usage": "活索结是一个可快速打开的绳结，用于临时固定小船或小动物。活索结在承重时会快速张紧，但是当拉动自由端时它会瞬间释放。",
    "feature": "属于“快松结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k232.jpg"
  },
  {
    "id": "k233",
    "name": "马贼索",
    "english": "Highwayman's Hitch；Highwayman's Cutaway；Dick Turpin's Knot；Highwayman's Getaway；Boat Hitch；Draw Hitch",
    "alias": "牧童结",
    "category": "快松结",
    "categoryId": "cat_11",
    "usage": "马贼索 能很快解开，一般是临时要固定一根绳索，之后又需要能轻松地全部解开时使用。这种绳结在工作端用力一拉便可解开。通常被用来临时性地把动物或船只固定在竿子旁。",
    "feature": "属于“快松结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k233.jpg"
  },
  {
    "id": "k234",
    "name": "敲钟的人结",
    "english": "Bell Ringer's Knot；Half Sheepshank",
    "alias": "",
    "category": "快松结",
    "categoryId": "cat_11",
    "usage": "暂无用途说明，可后续补充。",
    "feature": "属于“快松结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k234.jpg"
  },
  {
    "id": "k235",
    "name": "西伯利亚套结",
    "english": "Siberian Hitch；Evenk Knot",
    "alias": "鄂温克结",
    "category": "快松结",
    "categoryId": "cat_11",
    "usage": "西伯利亚套结被用来把绳子系在一个物体上。该绳结捆绑起来很方便，即使在寒冷的天气情况下，戴了厚厚的分指或连指手套都可以打结。作为一个活结，它可以很快解开，只需拉一下该绳索的工作端即可。西伯利亚套结适合一般的、非重要的场合，比如，固定防水布的绷绳。它不适合要求比较高的情况。",
    "feature": "属于“快松结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k235.jpg"
  },
  {
    "id": "k236",
    "name": "鞋带结",
    "english": "Bow Knot；Shoelace Knot；Slipped Reef Knot；Slipped Square Knot",
    "alias": "蝴蝶结",
    "category": "快松结",
    "categoryId": "cat_11",
    "usage": "鞋带结通常用来系鞋带，打结和解开都很容易。",
    "feature": "属于“快松结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k236.jpg"
  },
  {
    "id": "k237",
    "name": "双套滑结",
    "english": "Slipped Clove Hitch；Quick Release Clove Hitch；Slippery Hitch",
    "alias": "快解双套结",
    "category": "快松结",
    "categoryId": "cat_11",
    "usage": "双套滑结用于将绳索临时连接到柱子或栏杆上，可以快速轻松地解开。",
    "feature": "属于“快松结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k237.jpg"
  },
  {
    "id": "k238",
    "name": "滑收缩结",
    "english": "Slipped Constrictor Knot",
    "alias": "",
    "category": "快松结",
    "categoryId": "cat_11",
    "usage": "收缩结是最有效的捆绑结之一。它简单、牢固，一旦系紧后很难或者不可能解开。收缩结适合于需要临时固定或者半永久绑定的情况。收缩结当作软管夹或者电缆夹也很好用。这种绳结是收缩结（Constrictor knot）的快速松解版本。",
    "feature": "属于“快松结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k238.jpg"
  },
  {
    "id": "k239",
    "name": "滑接绳结",
    "english": "Tiller's Hitch；Slipped Sheet Bend；Quick Release Sheet Bend；Slipped Becket Bend",
    "alias": "",
    "category": "快松结",
    "categoryId": "cat_11",
    "usage": "滑接绳结是快速解结的接绳结。历史上，该结曾被用作固定一条船上抽屉的临时绳结。",
    "feature": "属于“快松结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k239.jpg"
  },
  {
    "id": "k240",
    "name": "滑拉普结",
    "english": "Slipped Lapp Knot；Slipped Lapp Bend；Adjustable Drawstring Knot；Gym Shorts Knot；Quick Hitch",
    "alias": "",
    "category": "快松结",
    "categoryId": "cat_11",
    "usage": "这种绳结很受欢迎，可用于运动短裤和类似装备（运动裤、泳裤、手术衣等）或浴袍上的可调节拉绳。它也可以用作捆状或卷状物品的捆扎结。",
    "feature": "属于“快松结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k240.jpg"
  },
  {
    "id": "k241",
    "name": "法里蒙摩擦结",
    "english": "Farrimond Friction Hitch",
    "alias": "",
    "category": "快松结",
    "categoryId": "cat_11",
    "usage": "法里蒙摩擦结是一种用于绳索受拉状态下使用的可快速释放、可调节摩擦绳结。",
    "feature": "属于“快松结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k241.jpg"
  },
  {
    "id": "k242",
    "name": "快速连接结",
    "english": "Quick Hitch；Slipped Lapp Knot",
    "alias": "速套结；滑拉普结",
    "category": "快松结",
    "categoryId": "cat_11",
    "usage": "这种绳结通常由树艺师使用，是拉起第二根绳索的简单快捷的方法。也很容易快速解开。",
    "feature": "属于“快松结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k242.jpg"
  },
  {
    "id": "k243",
    "name": "三套称人结",
    "english": "Triple Bowline；Three Loop Bowline",
    "alias": "",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "三套称人结用于在绳索中间形成三个固定环，可以在不接触末端得情况下进行捆扎。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k243.jpg"
  },
  {
    "id": "k244",
    "name": "优胜美地称人结",
    "english": "Yosemite Bowline；Bowline with Yosemite Finish；Retraced Bowline；Tucked Bowline",
    "alias": "優勝美地布林結",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "优胜美地称人结比一般的称人结更加牢固。人们把称人结的自由端绕在绳圈的一端，然后将自由端从绳结处拉回来---通常被称作“优胜美地终端”。这类绳结用途广泛，登山者可以很轻松地用它把攀登绳索套在自己的背带上。八字环结是最常见的选择，因为人们对它更熟悉。优胜美地称人结的优点有，当潮湿、结冰的时候容易解开，一只手就有可能绑好，绳结更简单，便于人们检查。建议把优胜美地称人结加个绳尾结比如双重反手结，这样就会更加牢固和安全。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k244.jpg"
  },
  {
    "id": "k245",
    "name": "爱德华兹称人结",
    "english": "Edwards Bowline；Butler's Bowline；Harry Butler's Yosemite Bowline",
    "alias": "",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "爱德华兹称人结是一种用于攀爬的环形结。它比常见的称人结更安全。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k245.jpg"
  },
  {
    "id": "k246",
    "name": "水中称人结",
    "english": "Water Bowline；Clove Hitch Bowline",
    "alias": "水上称人结",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "水中称人结是专为潮湿环境中使用的一种绳结，例如在拖动一条船时，而其他绳结会打滑或死结。虽然结成后的外观与双称人结类似,但水中称人结在绳尾部分用双套结形成一个绳环。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k246.jpg"
  },
  {
    "id": "k247",
    "name": "活称人结",
    "english": "Running Bowline；Running Bowline Knot",
    "alias": "",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "活称人结是一种套索，结构上与标准称人结有关。像大多数活结，活称人结在受拉时会自动张紧，但当拉力消除时会解开。与标准称人结一样，它容易滑动，甚至在长期使用也容易解开。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k247.jpg"
  },
  {
    "id": "k248",
    "name": "卡尔梅克结",
    "english": "Kalmyk Loop；Slipped Inuit Bowline",
    "alias": "卡尔梅克环",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "西方人大多数不认识卡尔梅克结，但在俄罗斯则很普遍，并且在需要固定线环时经常用来代替常见的称人结。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k248.jpg"
  },
  {
    "id": "k249",
    "name": "葡萄牙称人结",
    "english": "Portuguese Bowline；French Bowline；Equalizing Bowline",
    "alias": "",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "葡萄牙称人结是称人结的一种变形，设有两个圆环，且可大可小。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k249.jpg"
  },
  {
    "id": "k250",
    "name": "西班牙称人结",
    "english": "Spanish Bowline",
    "alias": "",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "西班牙称人结是可用于将人托起的一种双环结。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k250.jpg"
  },
  {
    "id": "k251",
    "name": "斯科特锁定称人结",
    "english": "Scott's Locker Bwoline；Secured Bowline",
    "alias": "安全称人结",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "斯科特锁定称人结是一种用于攀爬的环形结。它比常见的称人结更安全。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k251.jpg"
  },
  {
    "id": "k252",
    "name": "双环称人结",
    "english": "Double Bowline；Round Turn Bowline；Double-Knotted Bowline",
    "alias": "双布林结",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "双环称人结是用于攀岩的两种常用绳结之一，另一个是八字套结。与八字套结相比，双称人结的一个优点是系重后更容易解开。虽然它比标准的称人结牢固，但是双环称人结没有八字套结牢固。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k252.jpg"
  },
  {
    "id": "k253",
    "name": "双称人结",
    "english": "Bowline on a Bight；Bosun's Chair；Y-Hang；Bowline upon the Bight；Two Loop Bowline",
    "alias": "",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "双称人结是绳索中央有一对大小固定绳环的结子。它的优点是绳环不会滑脱，张紧后较容易解开。急救时，双称人结可用作提升椅。当需要一个牢固的绳环但是无法接触任意绳端时，该结是很方便的。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k253.jpg"
  },
  {
    "id": "k254",
    "name": "双称人结（2）",
    "english": "Rethreaded Bowline；Retraced Bowline；Bowline on a Bight；Bowline Follow Thru；Bowline upon the Bight",
    "alias": "",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "双称人结是绳索中央有一对大小固定绳环的结子。它的优点是绳环不会滑脱，张紧后较容易解开。急救时，双称人结可用作提升椅。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k254.jpg"
  },
  {
    "id": "k255",
    "name": "哥萨克结",
    "english": "Inuit Bowline；Sitka Loop；Cossack Knot；Anti-Bowline；Boas Bowline",
    "alias": "爱斯基摩称人结",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "哥萨克结比普通的称人结更安全，特别是用于合成线上和线环被拉紧的时候。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k255.jpg"
  },
  {
    "id": "k256",
    "name": "称人结",
    "english": "Bowline；Boling Knot；Bowline Knot；Standing Bowline",
    "alias": "帆索结；布林结；单套结",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "称人结用于在绳端形成一个固定的绳环。称人结通常用于航海，也可用于系绑轻型飞机。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k256.jpg"
  },
  {
    "id": "k257",
    "name": "称人结（荷兰）",
    "english": "Cowboy Bowline；Left-hand Bowline；Dutch Bowline；Dutch Marine Bowline；Winter Bowline",
    "alias": "",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "称人结用于在绳端形成一个固定的绳环。称人结是著名的救援结，用于援救从悬崖坠到岩架或坠入洞中的人员。称人结通常用于航海，也可用于系绑轻型飞机。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k257.jpg"
  },
  {
    "id": "k258",
    "name": "称人结（快速）",
    "english": "Snap Bowline；Quick Bowline；Bowline；Boling Knot；Bowline Knot；Standing Bowline",
    "alias": "称人结；帆索结；布林结；单套结",
    "category": "称人结系列",
    "categoryId": "cat_12",
    "usage": "称人结用于在绳端形成一个固定的绳环。称人结通常用于航海，也可用于系绑轻型飞机。",
    "feature": "属于“称人结系列”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k258.jpg"
  },
  {
    "id": "k259",
    "name": "三重反手结",
    "english": "Triple Overhand Knot；Franciscan Friar's Knot；Threefold Overhand Knot；Barrel Knot；Friar's Knot；French Monk's Knot；Monk's Knot；Hoodie String Knot",
    "alias": "",
    "category": "绳尾结",
    "categoryId": "cat_13",
    "usage": "暂无用途说明，可后续补充。",
    "feature": "属于“绳尾结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k259.jpg"
  },
  {
    "id": "k260",
    "name": "三重滚结",
    "english": "Triple Roll",
    "alias": "",
    "category": "绳尾结",
    "categoryId": "cat_13",
    "usage": "暂无用途说明，可后续补充。",
    "feature": "属于“绳尾结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k260.jpg"
  },
  {
    "id": "k261",
    "name": "多个反手结",
    "english": "Multiple Overhand Knot；Heaving Line Knot；Multi-fold Overhand Knot；French Knot；Quipu；Khipu",
    "alias": "桶结；血结",
    "category": "绳尾结",
    "categoryId": "cat_13",
    "usage": "暂无用途说明，可后续补充。",
    "feature": "属于“绳尾结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k261.jpg"
  },
  {
    "id": "k262",
    "name": "猴拳结",
    "english": "Monkey's Fist；Monkey's Paw；Slungshot",
    "alias": "猴拳结；猴子拳头结",
    "category": "绳尾结",
    "categoryId": "cat_13",
    "usage": "猴拳结之所以被如此命名是因为它看起来像一个小的，攥着的拳头或爪子。它被绑在绳子的末端形成一个重量，使绳子更容易的抛出，也可作为一个装饰结。",
    "feature": "属于“绳尾结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k262.jpg"
  },
  {
    "id": "k263",
    "name": "电工结",
    "english": "Underwriter's Knot；Electrician's Knot；Two-strand Wall Knot",
    "alias": "",
    "category": "绳尾结",
    "categoryId": "cat_13",
    "usage": "电工结在电气应用中用于降低电线终端的拉力。",
    "feature": "属于“绳尾结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k263.jpg"
  },
  {
    "id": "k264",
    "name": "八字结",
    "english": "Figure Eight；Flemish Knot；Savoy Knot；Figure of Eight Knot",
    "alias": "单八字结",
    "category": "绳尾结",
    "categoryId": "cat_13",
    "usage": "在许多情况下，八字结是替代普通反手结的一个通用止索结。在航海和攀岩中，八字结十分重要，因为需要止索结来阻止装置脱出。",
    "feature": "属于“绳尾结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k264.jpg"
  },
  {
    "id": "k265",
    "name": "艾希礼止索结",
    "english": "Ashley Stopper Knot；Oysterman's Stopper",
    "alias": "止索结",
    "category": "绳尾结",
    "categoryId": "cat_13",
    "usage": "在绳端，艾希礼止索结具有相当平衡的三面止动特性；当穿过开口时，它能比其他普通绳尾结提供更大的阻力。",
    "feature": "属于“绳尾结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k265.jpg"
  },
  {
    "id": "k266",
    "name": "抛绳结",
    "english": "Heaving Line Knot",
    "alias": "",
    "category": "绳尾结",
    "categoryId": "cat_13",
    "usage": "’抛绳结‘的一种，图片所示的绳结因为在末端提供了重量因此及其沉重，易于抛出。",
    "feature": "属于“绳尾结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k266.jpg"
  },
  {
    "id": "k267",
    "name": "抛绳结（2）",
    "english": "Capuchin；Uli Knot；Heaving Line Knot",
    "alias": "",
    "category": "绳尾结",
    "categoryId": "cat_13",
    "usage": "’抛绳结‘的一种，图片所示的绳结因为在末端提供了重量因此及其沉重，易于抛出。",
    "feature": "属于“绳尾结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k267.jpg"
  },
  {
    "id": "k268",
    "name": "双反手结",
    "english": "Double Overhand Knot；Blook Knot",
    "alias": "双单结",
    "category": "绳尾结",
    "categoryId": "cat_13",
    "usage": "双反手结主要是其他绳结的基础结，包括外科结的第一结和双渔人结的两侧。",
    "feature": "属于“绳尾结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k268.jpg"
  },
  {
    "id": "k269",
    "name": "反手结",
    "english": "Backhand Hitch；High Tie；High Safety Knot",
    "alias": "",
    "category": "绳尾结",
    "categoryId": "cat_13",
    "usage": "反手结通常在固定运送荷载时被用作锚。当绳索受力时，反手结很容易解开。",
    "feature": "属于“绳尾结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k269.jpg"
  },
  {
    "id": "k270",
    "name": "苦力结",
    "english": "Stevedore's Knot",
    "alias": "装卸结",
    "category": "绳尾结",
    "categoryId": "cat_13",
    "usage": "苦力结是一种止索结，通常结在绳端。该结常被码头工人装卸船货使用。为了升降货物，工人们使用大尺寸的滑车，这就需要使用较大的止索结来避免绳索从滑车中完全脱出。",
    "feature": "属于“绳尾结”类别。结构特点可根据实际绳结图和后续资料继续补充。",
    "image": "/images/knots/k270.jpg"
  }
]
